import test, { beforeEach } from 'node:test'
import assert from 'node:assert/strict'
import * as data from '../src/data.js'
import { clinicNow, setClockSource } from '../src/clock.js'
import { normalizeClinicState, sessionForRole, persistableCollection } from '../src/contracts.js'
import { createWorkflowActions } from '../src/workflow.js'
import { withServerAppointments } from './support/server-appointments.js'
import { pendingHours, visibleHmo, visibleNotifications, visibleConversations, notificationDestination, missingRequirements } from '../src/phase3-contracts.js'
import { automationSnapshot } from '../src/orchestration.js'
import { prescriptionTasks, visibleInvoices } from '../src/phase2.js'

let instant
beforeEach(()=>{instant='2026-09-19T02:08:00Z';setClockSource(()=>new Date(instant))})
const seedKeys={persons:'PERSONS',services:'SERVICES',branchServices:'BRANCH_SERVICES',dentistServiceAssignments:'DENTIST_SERVICE_ASSIGNMENTS',branches:'BRANCHES',dentists:'DENTISTS',staff:'STAFF',patients:'PATIENTS',users:'USERS',automations:'AUTOMATIONS'}
function fixture(patch={}) {
  const seeds=Object.fromEntries(Object.entries(seedKeys).map(([k,v])=>[k,structuredClone(data[`INITIAL_${v}`])]))
  seeds.users.push({id:'u13',personId:'per-p2',roleName:'Patient',status:'Active',permissions:['patient-portal']})
  seeds.patients=seeds.patients.map(p=>p.id==='p2'?{...p,userId:'u13'}:p)
  let state=normalizeClinicState({...seeds,appointments:[],visits:[],queue:[],treatments:[],invoices:[],prescriptions:[],followups:[],hmo:[],conversations:[],inquiries:[],notifications:[],workflowLog:[],audit:[],...patch})
  let session=sessionForRole('staff',state)
  const raw=createWorkflowActions({getState:()=>state,getSession:()=>session,commit:p=>{state=normalizeClinicState({...state,...p})}})
  // M6 cutover: server appointments; Check-In/No-show/treatment transitions run server-first.
  const server=withServerAppointments({getState:()=>state,setState:next=>{state=normalizeClinicState(next)},getSession:()=>session,rawActions:()=>raw})
  return {get actions(){return server.actions()},flow:server.flow,get state(){return state},get session(){return session},role(role,overrides={}){session={...sessionForRole(role,state),...overrides}},patch(p){state=normalizeClinicState({...state,...p})}}
}
const ok=result=>{assert.equal(result.ok,true,result.message);return result.record}
const form={patientId:'p1',branchId:'b1',dentistId:'d1',serviceId:'svc1',date:'2026-09-19',start:'11:00'}
function book(f,patch={}){return f.flow.book({...form,...patch})}
// M12: HMO cases are server-authoritative (backend/tests/Feature/Hmo); the browser has no HMO commands. Notification and
// workflow-event behaviour below is exercised through appointment notifications and conversation commands instead.
function announce(f,patch={}){const a=book(f,patch);ok(f.actions.recordAppointmentEvent(a.id,'created'));return a}
function complete(f,patch={}) {
  const a=book(f),q=ok(f.actions.checkInAppointment(a.id));f.role('dentist');ok(f.actions.updateQueue(q.id,'Called'));ok(f.actions.saveTreatment({queueEntryId:q.id}));return ok(f.actions.completeTreatment({queueEntryId:q.id,procedure:'Documented procedure',procedures:[{serviceId:'svc1',quantity:1}],...patch}))
}
function thread(f,patch={}) {
  const c={id:'c1',patientId:'p1',branchId:'b1',assignedUserId:'u2',participantUserIds:['u12','u2','u3'],unreadUserIds:['u12','u2','u3'],status:'Open',messages:[],readAtByUser:{},...patch}
  f.patch({conversations:[c]});return f.state.conversations[0]
}


test('appointment notification is created once and owned by exact patient user',()=>{const f=fixture(),a=book(f);ok(f.actions.recordAppointmentEvent(a.id,'created'));const before=f.state.notifications.length;ok(f.actions.recordAppointmentEvent(a.id,'created'));assert.equal(f.state.notifications.length,before);const n=f.state.notifications.find(n=>n.eventType==='appointment.created');assert.equal(n.patientId,'p1');assert.equal(n.recipientUserId,'u12');assert.equal(n.entityId,a.id);assert.ok(f.state.workflowLog.some(e=>e.id===n.eventId))})
// M5/M18 boundary: treatment completion and the transitional reconciliation create no notification. The Dentist's
// prescription task and Staff's Draft invoice are the M19/M11 worklist records themselves.
test('the prescription task belongs only to the treating Dentist and completion sends the Dentist no notification',()=>{const f=fixture();complete(f,{prescriptionRequired:true});assert.equal(visibleNotifications(f.state,f.session).length,0);assert.equal(prescriptionTasks(f.state,f.session).length,1);f.role('dentist',{userId:'u6',dentistId:'d2'});assert.equal(prescriptionTasks(f.state,f.session).length,0)})
test('the Draft invoice reaches Staff through billing scope, not a completion notification',()=>{const f=fixture();complete(f);f.role('staff');assert.equal(visibleNotifications(f.state,f.session).some(n=>n.type==='Invoice review needed'),false);assert.equal(visibleInvoices(f.state,f.session).length,1);f.role('staff',{userId:'u4',branchId:'b2'});assert.equal(visibleInvoices(f.state,f.session).length,0)})
test('M5 reconciliation creates no notification record of any kind and no browser HMO case',()=>{
  const f=fixture();complete(f,{prescriptionRequired:true,followupRequired:true})
  assert.ok(f.state.invoices.length===1&&f.state.followups.length===1)
  assert.equal(f.state.hmo.length,0,'M12: HMO cases are opened on the server by Staff, never by a browser handoff')
  assert.deepEqual(f.state.notifications,[],'no Visit Complete / Follow-Up Required / invoice / prescription / HMO notice')
  for(const n of f.state.notifications)assert.equal(n.channel,'In-App','no external channel')
  const before=structuredClone(f.state.notifications);f.role('staff');f.actions.reconcileTreatmentHandoffs();f.actions.reconcileTreatmentHandoffs();assert.deepEqual(f.state.notifications,before,'reconciling again adds nothing')
})
test('mark read changes only the exact notification recipient',()=>{const f=fixture();announce(f);const n=f.state.notifications.find(n=>n.recipientUserId==='u12');assert.equal(f.actions.markNotificationRead(n.id).ok,false);assert.equal(f.state.notifications.find(x=>x.id===n.id).read,false);f.role('patient');ok(f.actions.markNotificationRead(n.id));assert.ok(f.state.notifications.find(x=>x.id===n.id).readAt);assert.ok(f.state.notifications.filter(x=>x.recipientUserId==='u2').every(n=>!n.read))})
test('mark all read is identity-specific for two Dentists',()=>{const f=fixture();f.patch({notifications:[{id:'d1',recipientUserId:'u3',recipientRole:'dentist',dentistId:'d1',patientId:'p1',read:false},{id:'d2',recipientUserId:'u6',recipientRole:'dentist',dentistId:'d2',patientId:'p2',read:false}]});f.role('dentist');ok(f.actions.markAllNotificationsRead());assert.equal(f.state.notifications[0].read,true);assert.equal(f.state.notifications[1].read,false)})
test('patient mark-all never changes another patient read flags',()=>{const f=fixture();book(f);book(f,{patientId:'p2',start:'13:00'});f.role('patient');ok(f.actions.markAllNotificationsRead());assert.ok(f.state.notifications.filter(n=>n.patientId==='p1').every(n=>n.read));assert.ok(f.state.notifications.filter(n=>n.patientId==='p2').every(n=>!n.read))})
test('notification navigation preserves canonical entity and ignores forged action context',()=>{const f=fixture(),a=announce(f);f.role('patient');const n=visibleNotifications(f.state,f.session).find(n=>n.entityType==='appointment');const action=notificationDestination(f.state,f.session,{...n,action:{page:'appointments',context:{appointmentId:'wrong',patientId:'p2'}}});assert.equal(action.context.appointmentId,a.id);assert.equal(action.context.patientId,'p1');assert.equal(notificationDestination(f.state,f.session,{...n,entityId:'other'}),null)})
test('authorized prescription creates one private patient notification linked to its event',()=>{const f=fixture(),t=complete(f,{prescriptionRequired:true});const input={treatmentId:t.id,items:[{medication:'Private medication',dosage:'Private dose',instructions:'Private instructions'}]};ok(f.actions.authorizePrescription(input));const count=f.state.notifications.length;ok(f.actions.authorizePrescription(input));assert.equal(f.state.notifications.length,count);const n=f.state.notifications.find(n=>n.eventType==='prescription.authorized');assert.equal(n.recipientUserId,'u12');assert.ok(!n.body.includes('Private'));assert.ok(f.state.workflowLog.some(e=>e.id===n.eventId))})
test('invoice and receipt each notify once with exact invoice navigation',()=>{const f=fixture();complete(f);f.role('staff');const i=f.state.invoices[0];ok(f.actions.reviewInvoice(i.id));ok(f.actions.issueInvoice(i.id));ok(f.actions.issueInvoice(i.id));ok(f.actions.postPayment(i.id,'Cash',i.total));ok(f.actions.postPayment(i.id,'Cash',i.total));assert.equal(f.state.notifications.filter(n=>n.eventType==='billing.issue').length,1);assert.equal(f.state.notifications.filter(n=>n.eventType==='billing.payment').length,1);f.role('patient');const n=visibleNotifications(f.state,f.session).find(n=>n.eventType==='billing.payment');assert.equal(notificationDestination(f.state,f.session,n).context.invoiceId,i.id);assert.ok(f.state.workflowLog.some(e=>e.id===n.eventId))})
test('follow-up booking reschedule and cancellation generate distinct related notifications',()=>{const f=fixture();complete(f,{followupRequired:true});f.role('staff');const follow=f.state.followups[0],a=book(f,{start:'13:00'});ok(f.actions.linkFollowupAppointment(follow.id,a.id));f.flow.setAppointment(a.id,{status:'Confirmed'});ok(f.actions.recordAppointmentEvent(a.id,'rescheduled'));ok(f.flow.cancel(a.id));for(const type of ['followup.scheduled','followup.rescheduled','followup.cancelled']){const n=f.state.notifications.find(n=>n.eventType===type);assert.ok(n,type);assert.equal(n.entityId,a.id);assert.equal(n.recipientUserId,'u12')}})
test('legacy patient notifications do not become shared Staff notifications',()=>{const f=fixture({notifications:structuredClone(data.INITIAL_NOTIFICATIONS)});assert.equal(visibleNotifications(f.state,f.session).length,0);f.role('patient');assert.ok(visibleNotifications(f.state,f.session).every(n=>n.patientId==='p1'));f.role('dentist');assert.equal(visibleNotifications(f.state,f.session).length,0)})
test('foreground appointment reminders use clinic time and do not duplicate',()=>{const f=fixture();book(f);ok(f.actions.evaluateOperationalReminders());assert.equal(f.state.notifications.filter(n=>n.eventType==='appointment.reminder').length,1);assert.equal(f.actions.evaluateOperationalReminders().unchanged,true)})
test('significant delay notification is timestamp-based and once per queue encounter',()=>{const f=fixture(),a=book(f);ok(f.actions.checkInAppointment(a.id));instant='2026-09-19T03:00:00Z';ok(f.actions.evaluateOperationalReminders());ok(f.actions.evaluateOperationalReminders());assert.equal(f.state.notifications.filter(n=>n.eventType==='queue.delay').length,1)})

test('message read state is participant-specific and never updates notifications',()=>{const f=fixture();thread(f);book(f);const notifications=structuredClone(f.state.notifications);ok(f.actions.markConversationRead('c1'));assert.deepEqual(f.state.conversations[0].unreadUserIds,['u12','u3']);assert.ok(f.state.conversations[0].readAtByUser.u2);assert.deepEqual(f.state.notifications,notifications)})
test('patient cannot access another patient conversation',()=>{const f=fixture();thread(f);f.role('patient',{userId:'u13',patientId:'p2'});assert.equal(visibleConversations(f.state,f.session).length,0);assert.equal(f.actions.markConversationRead('c1').ok,false);assert.equal(f.actions.replyToConversation('c1','Unauthorized','reply').ok,false)})
test('Dentist role string alone never grants conversation access',()=>{const f=fixture();thread(f,{participantUserIds:['u12','u2'],assignedRole:'Dentist'});f.role('dentist');assert.equal(visibleConversations(f.state,f.session).length,0);assert.equal(f.actions.replyToConversation('c1','Unauthorized','reply').ok,false)})
test('unassigned legacy Dentist conversation is withheld instead of granting role access',()=>{const f=fixture({conversations:[{id:'legacy',patientId:'p1',assignedRole:'Dentist',status:'Open',messages:[]}]});f.role('dentist');assert.equal(visibleConversations(f.state,f.session).length,0);f.role('patient');assert.equal(visibleConversations(f.state,f.session).length,0)})
test('explicit legacy named assignee migrates to actual participant identity',()=>{const f=fixture({conversations:[{id:'legacy',patientId:'p1',assignedTo:'Dr. Miguel Reyes',assignedRole:'Dentist',status:'Open',unreadBy:['dentist'],messages:[]}]});assert.deepEqual(f.state.conversations[0].participantUserIds,['u12','u3']);f.role('dentist');assert.equal(visibleConversations(f.state,f.session).length,1);f.role('dentist',{userId:'u6',dentistId:'d2'});assert.equal(visibleConversations(f.state,f.session).length,0)})
test('Staff participant must also belong to conversation branch',()=>{const f=fixture();thread(f,{participantUserIds:['u12','u4']});f.role('staff',{userId:'u4',branchId:'b2'});assert.equal(visibleConversations(f.state,f.session).length,0);assert.equal(f.actions.replyToConversation('c1','Wrong branch','reply').ok,false)})
test('authorized reply updates exact thread and other participant unread state only',()=>{const f=fixture();thread(f,{unreadUserIds:[]});f.patch({conversations:[...f.state.conversations,{id:'other',patientId:'p2',branchId:'b2',participantUserIds:['u13','u4'],unreadUserIds:[],messages:[],status:'Open'}]});const other=structuredClone(f.state.conversations[1]);ok(f.actions.replyToConversation('c1','Hello patient','reply-1'));assert.equal(f.state.conversations[0].messages[0].senderUserId,'u2');assert.deepEqual(f.state.conversations[0].unreadUserIds,['u12','u3']);assert.deepEqual(f.state.conversations[1],other);assert.equal(f.state.notifications.length,0)})
test('reply retry is idempotent even after thread closes',()=>{const f=fixture();thread(f);ok(f.actions.replyToConversation('c1','Hello','reply'));ok(f.actions.closeConversation('c1'));assert.equal(f.actions.replyToConversation('c1','Hello','reply').unchanged,true);assert.equal(f.state.conversations[0].messages.length,1);assert.equal(f.actions.replyToConversation('c1','Another','reply-2').ok,false)})
test('closing conversation preserves other participant unread flags',()=>{const f=fixture();thread(f);ok(f.actions.closeConversation('c1'));assert.deepEqual(f.state.conversations[0].unreadUserIds,['u12','u2','u3'])})
test('inquiry conversion links appointment and conversation exactly once',()=>{const f=fixture(),a=book(f),i=ok(f.actions.createInquiry({name:'Contact',topic:'Booking',source:'Website'},'inquiry-create'));ok(f.actions.updateInquiry(i.id,'Responded'));const converted=ok(f.actions.convertInquiry(i.id,a.id));assert.equal(converted.bookedAppointmentId,a.id);assert.equal(f.state.conversations[0].inquiryId,i.id);assert.equal(f.state.conversations[0].patientId,a.patientId);assert.deepEqual(f.state.conversations[0].participantUserIds,['u2','u12']);const count=f.state.workflowLog.length;assert.equal(f.actions.convertInquiry(i.id,a.id).unchanged,true);assert.equal(f.state.conversations.length,1);assert.equal(f.state.workflowLog.length,count)})
test('inquiry conversion rejects different assigned branch and duplicate relinking',()=>{const f=fixture(),a=book(f),i=ok(f.actions.createInquiry({name:'Contact',topic:'Booking'},'inquiry'));ok(f.actions.convertInquiry(i.id,a.id));const other=book(f,{start:'13:00'});assert.equal(f.actions.convertInquiry(i.id,other.id).ok,false);f.role('staff',{userId:'u4',branchId:'b2'});assert.equal(f.actions.convertInquiry(i.id,a.id).ok,false)})

test('completion retains one Phase 2 chain alongside HMO and notification orchestration',()=>{const f=fixture(),t=complete(f,{prescriptionRequired:true,followupRequired:true});const before=structuredClone(f.state);ok(f.actions.completeTreatment({queueEntryId:t.queueEntryId}));assert.deepEqual(f.state,before);assert.equal(f.state.invoices.length,1);assert.equal(f.state.followups.length,1);assert.equal(f.state.hmo.length,0);assert.equal(f.state.workflowLog.filter(e=>e.eventType==='clinical.treatment.completed').length,1)})
test('workflow events contain exact entity context actor and timestamp',()=>{const f=fixture(),a=announce(f),e=f.state.workflowLog.find(e=>e.eventType==='appointment.created');assert.equal(e.entityType,'appointment');assert.equal(e.entityId,a.id);assert.equal(e.appointmentId,a.id);assert.equal(e.patientId,'p1');assert.equal(e.branchId,'b1');assert.equal(e.actorUserId,'u2');assert.equal(e.createdAt,clinicNow().timestamp)})
test('failed command preserves business state and does not log false Success',()=>{const f=fixture();thread(f);const before=structuredClone(f.state.conversations),success=f.state.workflowLog.filter(e=>e.status==='Success').length;assert.equal(f.actions.replyToConversation('c1','   ','bad').ok,false);assert.deepEqual(f.state.conversations,before);assert.equal(f.state.workflowLog.filter(e=>e.status==='Success').length,success);assert.equal(f.state.workflowLog[0].status,'Failed');assert.equal(f.state.workflowLog[0].entityId,'c1')})
test('repeated failure attempt is deduplicated and does not create render-time logs',()=>{const f=fixture();thread(f);f.actions.replyToConversation('c1','   ','bad');const before=structuredClone(f.state);f.actions.replyToConversation('c1','   ','bad');assert.deepEqual(f.state,before);automationSnapshot(f.state);visibleHmo(f.state,f.session);visibleNotifications(f.state,f.session);assert.deepEqual(f.state,before)})
test('Automation Monitor reads events and warnings without mutating protected rules',()=>{const f=fixture();f.patch({services:f.state.services.map(s=>s.id==='svc1'?{...s,baseFee:NaN}:s)});complete(f);const before=structuredClone(f.state);const monitor=automationSnapshot(f.state);assert.equal(monitor.warnings.length,1);assert.equal(monitor.rules.length,6);assert.deepEqual(f.state,before)})
test('Phase 3 records survive ID-only persistence and normalization without events',()=>{const f=fixture(),a=announce(f);thread(f);ok(f.actions.replyToConversation('c1','Persist me','reply'));const before=structuredClone(f.state);const patch=Object.fromEntries(['notifications','conversations','inquiries'].map(k=>[k,JSON.parse(JSON.stringify(persistableCollection(k,f.state[k])))]));f.patch(patch);assert.equal(f.state.notifications.find(n=>n.recipientUserId==='u12').entityId,a.id);assert.equal(f.state.conversations[0].messages[0].senderUserId,'u2');assert.deepEqual(f.state.workflowLog,before.workflowLog)})

test('expired session cannot read or mark recipient notification',()=>{const f=fixture();book(f);f.role('patient');f.patch({users:f.state.users.map(u=>u.id==='u12'?{...u,status:'Inactive',accountStatus:'Inactive'}:u)});assert.equal(visibleNotifications(f.state,f.session).length,0);assert.equal(f.actions.markAllNotificationsRead().ok,false)})
test('same-branch Staff mark-all cannot alter another Staff identity',()=>{const f=fixture();f.patch({users:[...f.state.users,{id:'staff-other',roleName:'Receptionist',status:'Active',branchId:'b1',permissions:['hmo']}],notifications:[{id:'mine',recipientUserId:'u2',recipientRole:'staff',branchId:'b1',read:false},{id:'other',recipientUserId:'staff-other',recipientRole:'staff',branchId:'b1',read:false}]});ok(f.actions.markAllNotificationsRead());assert.equal(f.state.notifications[0].read,true);assert.equal(f.state.notifications[1].read,false)})
test('broad Dentist notification role cannot replace recipient identity',()=>{const f=fixture({notifications:[{id:'broad',recipientRole:'dentist',patientId:'p1',dentistId:'d1',read:false}]});f.role('dentist');assert.equal(visibleNotifications(f.state,f.session).length,0)})
test('message reply command cannot be replayed as another participant',()=>{const f=fixture();thread(f);ok(f.actions.replyToConversation('c1','Staff reply','same'));f.role('patient');assert.equal(f.actions.replyToConversation('c1','Patient reply','same').ok,false);assert.equal(f.state.conversations[0].messages.length,1)})
test('Patient cannot close a conversation or access it using forged patientId',()=>{const f=fixture();thread(f);f.role('patient');assert.equal(f.actions.closeConversation('c1').ok,false);f.role('patient',{patientId:'p2'});assert.equal(visibleConversations(f.state,f.session).length,0)})
test('Owner oversight does not grant conversation participation',()=>{const f=fixture();thread(f,{participantUserIds:['u1','u12']});f.role('owner');assert.equal(visibleConversations(f.state,f.session).length,0);assert.equal(f.actions.replyToConversation('c1','Owner reply','owner').ok,false)})
test('legacy ownership ambiguity remains withheld after persistence',()=>{const f=fixture({conversations:[{id:'legacy',patientId:'p1',assignedRole:'Dentist',assignedTo:'Unknown Dentist',status:'Open',messages:[]}]});const persisted=persistableCollection('conversations',f.state.conversations);f.patch({conversations:JSON.parse(JSON.stringify(persisted))});f.role('dentist');assert.equal(visibleConversations(f.state,f.session).length,0)})
test('notification selectors retain full history rather than an eight-record data limit',()=>{const f=fixture();f.patch({notifications:Array.from({length:20},(_,i)=>({id:`n${i}`,recipientUserId:'u12',recipientRole:'patient',patientId:'p1',read:false}))});f.role('patient');assert.equal(visibleNotifications(f.state,f.session).length,20)})
test('legacy static pending hours never survive canonical persistence',()=>{const f=fixture({hmo:structuredClone(data.INITIAL_HMO)});const saved=persistableCollection('hmo',f.state.hmo);assert.ok(saved.every(h=>!Object.hasOwn(h,'pendingHours')));assert.ok(saved.every(h=>h.branchId&&h.providerId))})
test('empty and closed message attempts cannot append messages or notifications',()=>{const f=fixture();thread(f);assert.equal(f.actions.replyToConversation('c1','  ','empty').ok,false);ok(f.actions.closeConversation('c1'));assert.equal(f.actions.replyToConversation('c1','text','closed').ok,false);assert.equal(f.state.conversations[0].messages.length,0);assert.equal(f.state.notifications.length,0)})

test('historical local eligibility flag is never projected as verified provider approval',()=>{const f=fixture({hmo:structuredClone(data.INITIAL_HMO)});const pending=f.state.hmo.find(h=>h.status==='Pending');assert.equal(pending.eligibility,'Awaiting external provider response');assert.notEqual(pending.eligibility,'Verified')})

test('reply command cannot be replayed against another authorized conversation',()=>{const f=fixture();const c=thread(f);f.patch({conversations:[c,{...c,id:'c2'}]});ok(f.actions.replyToConversation('c1','First','reply'));assert.equal(f.actions.replyToConversation('c2','Wrong thread','reply').ok,false);assert.equal(f.state.conversations.find(c=>c.id==='c2').messages.length,0)})

test('HMO views reject inactive accounts and mismatched Dentist identity',()=>{
  const f=fixture();complete(f);f.role('dentist',{userId:'u6',dentistId:'d1'});assert.equal(visibleHmo(f.state,f.session).length,0)
  f.role('patient');f.patch({users:f.state.users.map(u=>u.id==='u12'?{...u,status:'Inactive',accountStatus:'Inactive'}:u)});assert.equal(visibleHmo(f.state,f.session).length,0)
})
test('unresolved legacy assignee labels survive persistence without granting access',()=>{
  const f=fixture({conversations:[{id:'legacy',patientId:'p1',assignedTo:'Unknown person',assignedRole:'Dentist',messages:[]}],inquiries:[{id:'legacy-inquiry',assigned:'Unknown person'}]})
  assert.equal(persistableCollection('conversations',f.state.conversations)[0].assignedTo,'Unknown person')
  assert.equal(persistableCollection('inquiries',f.state.inquiries)[0].assigned,'Unknown person')
  f.role('dentist');assert.equal(visibleConversations(f.state,f.session).length,0)
})
test('malformed legacy document metadata does not imply local completeness',()=>{
  const f=fixture({hmo:[{id:'legacy',patientId:'p1',branchId:'b1',providerId:'hmo-medicare',status:'Draft',documents:{unexpected:true}}]})
  assert.equal(missingRequirements(f.state.hmo[0]).length,3)
})
