import test, { beforeEach } from 'node:test'
import assert from 'node:assert/strict'
import * as data from '../src/data.js'
import { clinicNow, setClockSource } from '../src/clock.js'
import { normalizeClinicState, sessionForRole, persistableCollection } from '../src/contracts.js'
import { createWorkflowActions } from '../src/workflow.js'
import { pendingHours, visibleHmo, visibleNotifications, visibleConversations, notificationDestination, missingRequirements } from '../src/phase3-contracts.js'
import { automationSnapshot } from '../src/orchestration.js'

let instant
beforeEach(()=>{instant='2026-09-19T02:08:00Z';setClockSource(()=>new Date(instant))})
const seedKeys={persons:'PERSONS',services:'SERVICES',branchServices:'BRANCH_SERVICES',dentistServiceAssignments:'DENTIST_SERVICE_ASSIGNMENTS',branches:'BRANCHES',dentists:'DENTISTS',staff:'STAFF',patients:'PATIENTS',users:'USERS',automations:'AUTOMATIONS'}
function fixture(patch={}) {
  const seeds=Object.fromEntries(Object.entries(seedKeys).map(([k,v])=>[k,structuredClone(data[`INITIAL_${v}`])]))
  seeds.users.push({id:'u13',personId:'per-p2',roleName:'Patient',status:'Active',permissions:['patient-portal']})
  seeds.patients=seeds.patients.map(p=>p.id==='p2'?{...p,userId:'u13'}:p)
  let state=normalizeClinicState({...seeds,appointments:[],queue:[],checkIns:[],treatments:[],invoices:[],prescriptions:[],followups:[],hmo:[],conversations:[],inquiries:[],notifications:[],workflowLog:[],audit:[],...patch})
  let session=sessionForRole('staff',state)
  const actions=createWorkflowActions({getState:()=>state,getSession:()=>session,commit:p=>{state=normalizeClinicState({...state,...p})}})
  return {actions,get state(){return state},get session(){return session},role(role,overrides={}){session={...sessionForRole(role,state),...overrides}},patch(p){state=normalizeClinicState({...state,...p})}}
}
const ok=result=>{assert.equal(result.ok,true,result.message);return result.record}
const form={patientId:'p1',branchId:'b1',dentistId:'d1',serviceId:'svc1',date:'2026-09-19',start:'11:00'}
function book(f,patch={}){return ok(f.actions.saveAppointment({...form,...patch}))}
function create(f){const a=book(f);return ok(f.actions.createHmoCase({appointmentId:a.id}))}
function ready(f,h=create(f)){for(const r of h.requirements)ok(f.actions.provideHmoRequirement(h.id,r.ruleId,{fileName:`${r.ruleId}.pdf`}));return f.state.hmo.find(x=>x.id===h.id)}
function submit(f,h=ready(f),commandId='submit-1'){return ok(f.actions.submitHmoCase(h.id,{commandId,method:'Portal',note:'Staff recorded external submission'}))}
const response=(h,outcome='Approved',commandId='response-1')=>({caseId:h.id,submissionCycle:h.submissionCycle,outcome,commandId,method:'Email',note:'Internal externally received response',requirementIds:outcome==='Returned'?['valid-id']:[]})
function contact(f,h,commandId='contact-1'){return ok(f.actions.followUpHmo(h.id,{submissionCycle:h.submissionCycle,commandId,method:'Phone',note:'Internal contact note',nextAction:'Await response'}))}
function complete(f,patch={}) {
  const a=book(f),q=ok(f.actions.checkInAppointment(a.id));f.role('dentist');ok(f.actions.updateQueue(q.id,'Called'));ok(f.actions.saveTreatment({queueEntryId:q.id}));return ok(f.actions.completeTreatment({queueEntryId:q.id,procedure:'Documented procedure',procedures:[{serviceId:'svc1',quantity:1}],...patch}))
}
function thread(f,patch={}) {
  const c={id:'c1',patientId:'p1',branchId:'b1',assignedUserId:'u2',participantUserIds:['u12','u2','u3'],unreadUserIds:['u12','u2','u3'],status:'Open',messages:[],readAtByUser:{},...patch}
  f.patch({conversations:[c]});return f.state.conversations[0]
}

test('qualifying case creation is idempotent for the exact appointment',()=>{const f=fixture(),h=create(f),n=f.state.notifications.length,e=f.state.workflowLog.length;assert.equal(f.actions.createHmoCase({appointmentId:h.appointmentId}).unchanged,true);assert.equal(f.state.hmo.length,1);assert.equal(f.state.notifications.length,n);assert.equal(f.state.workflowLog.length,e)})
test('completion prepares one HMO case with exact treatment patient appointment branch and provider',()=>{const f=fixture(),t=complete(f),h=f.state.hmo[0];for(const k of ['patientId','branchId','appointmentId'])assert.equal(h[k],t[k]);assert.equal(h.treatmentId,t.id);assert.equal(h.providerId,'hmo-medicare');assert.equal(h.providerOutcome,null);const events=f.state.workflowLog.length;assert.equal(f.actions.completeTreatment({queueEntryId:t.queueEntryId}).unchanged,true);assert.equal(f.state.hmo.length,1);assert.equal(f.state.workflowLog.length,events)})
test('appointment HMO case is reused and linked on treatment completion',()=>{const f=fixture(),a=book(f),h=ok(f.actions.createHmoCase({appointmentId:a.id})),q=ok(f.actions.checkInAppointment(a.id));f.role('dentist');ok(f.actions.updateQueue(q.id,'Called'));ok(f.actions.saveTreatment({queueEntryId:q.id}));const t=ok(f.actions.completeTreatment({queueEntryId:q.id,procedure:'Completed',procedures:[{serviceId:'svc1',quantity:1}]}));assert.equal(f.state.hmo.length,1);assert.equal(f.state.hmo[0].id,h.id);assert.equal(f.state.hmo[0].treatmentId,t.id)})
test('uninsured encounter does not create HMO case',()=>{const f=fixture();f.patch({patients:f.state.patients.map(p=>p.id==='p1'?{...p,hmo:'None',hmoProviderId:null,hmoMember:'—'}:p)});complete(f);assert.equal(f.state.hmo.length,0)})
test('missing requirements are deterministic; local validation is not provider approval',()=>{const f=fixture(),h=create(f);assert.equal(missingRequirements(h).length,3);const r=ready(f,h);assert.equal(r.status,'Ready for Submission');assert.equal(r.providerOutcome,null);assert.equal(missingRequirements(r).length,0)})
test('patient document metadata requires Staff local validation',()=>{const f=fixture(),h=create(f);f.role('patient');ok(f.actions.provideHmoRequirement(h.id,'valid-id',{fileName:'patient-id.pdf',size:123}));assert.equal(f.state.hmo[0].requirements.find(r=>r.ruleId==='valid-id').state,'Provided');assert.equal(f.actions.submitHmoCase(h.id,{commandId:'unauthorized'}).ok,false);f.role('staff');ok(f.actions.provideHmoRequirement(h.id,'valid-id'));assert.equal(f.state.hmo[0].requirements.find(r=>r.ruleId==='valid-id').state,'Validated locally')})
for(const outcome of ['Approved','Rejected'])test(`Staff records externally received provider ${outcome}`,()=>{const f=fixture(),h=submit(f);const r=ok(f.actions.recordHmoOutcome(h.id,response(h,outcome)));assert.equal(r.status,outcome);assert.equal(r.responses[0].externalResponseRecorded,true);assert.equal(r.responses[0].recordedBy,'u2');assert.equal(r.responses[0].caseId,h.id);assert.ok(r.providerRespondedAt);assert.equal(r.responses[0].providerVerified,undefined)})
test('Returned case can be corrected and resubmitted under the same case ID',()=>{const f=fixture(),h=submit(f);ok(f.actions.recordHmoOutcome(h.id,response(h,'Returned')));assert.equal(f.state.hmo[0].status,'Returned');assert.equal(missingRequirements(f.state.hmo[0]).length,1);assert.equal(f.actions.submitHmoCase(h.id,{commandId:'too-early',method:'Portal',note:'Corrected'}).ok,false);ok(f.actions.provideHmoRequirement(h.id,'valid-id',{fileName:'corrected-id.pdf'}));const second=submit(f,f.state.hmo[0],'resubmit-2');assert.equal(second.id,h.id);assert.equal(second.submissionCycle,2);assert.equal(second.providerOutcome,null);assert.equal(second.responses.length,1);assert.equal(f.actions.recordHmoOutcome(h.id,response(h,'Approved','stale')).ok,false);ok(f.actions.recordHmoOutcome(h.id,response(second,'Approved','response-2')))})
test('Escalated case stays pending and accepts contacts and provider response',()=>{const f=fixture(),h=submit(f);instant='2026-09-19T15:08:00Z';ok(f.actions.evaluateHmoTimers());contact(f,h);const e=ok(f.actions.escalateHmo(h.id));assert.equal(e.status,'Escalated');assert.equal(e.providerOutcome,null);contact(f,e,'contact-2');ok(f.actions.recordHmoOutcome(e.id,response(e)));assert.equal(f.state.hmo[0].status,'Approved')})
test('pending duration derives from Manila timestamps and the controlled clock',()=>{const f=fixture(),h=submit(f);assert.equal(pendingHours(h),0);instant='2026-09-19T15:08:00Z';assert.equal(pendingHours({...h,pendingHours:999}),13);assert.equal(pendingHours({status:'Pending',submittedAt:'2026-09-19 10:08'}),13);ok(f.actions.recordHmoOutcome(h.id,response(h)));instant='2026-09-20T15:08:00Z';assert.equal(pendingHours(f.state.hmo[0]),13)})
test('overdue evaluation creates one task, warning event and per-recipient alert',()=>{const f=fixture(),h=submit(f);instant='2026-09-19T15:08:00Z';ok(f.actions.evaluateHmoTimers());const before=structuredClone(f.state);assert.equal(f.actions.evaluateHmoTimers().unchanged,true);assert.deepEqual(f.state,before);assert.equal(f.state.hmo[0].followUpTasks.length,1);const alerts=f.state.notifications.filter(n=>n.eventType==='hmo.followup.required');assert.equal(alerts.length,1);assert.equal(alerts[0].recipientUserId,'u2');assert.equal(alerts[0].entityId,h.id)})
test('contact and escalation retries do not duplicate records or events',()=>{const f=fixture(),h=submit(f);instant='2026-09-19T15:08:00Z';contact(f,h);const count=f.state.workflowLog.length;contact(f,h);assert.equal(f.state.hmo[0].contacts.length,1);assert.equal(f.state.workflowLog.length,count);ok(f.actions.escalateHmo(h.id));const before=structuredClone(f.state);assert.equal(f.actions.escalateHmo(h.id).unchanged,true);assert.deepEqual(f.state,before)})
test('contact log includes exact case Staff time method note and next action',()=>{const f=fixture(),h=submit(f);const r=contact(f,h),c=r.contacts[0];assert.equal(c.caseId,h.id);assert.equal(c.staffUserId,'u2');assert.equal(c.at,clinicNow().timestamp);assert.equal(c.method,'Phone');assert.equal(c.note,'Internal contact note');assert.equal(c.nextAction,'Await response');assert.equal(r.providerOutcome,null)})
test('patient HMO projection hides contact logs internal response notes and membership',()=>{const f=fixture(),h=submit(f);contact(f,h);ok(f.actions.recordHmoOutcome(h.id,response(h)));f.role('patient');const own=visibleHmo(f.state,f.session);assert.equal(own.length,1);for(const key of ['contacts','responses','memberId','submissionHistory','escalatedBy'])assert.equal(own[0][key],undefined);assert.ok(!JSON.stringify(own).includes('Internal'));f.role('patient',{userId:'u13',patientId:'p2'});assert.equal(visibleHmo(f.state,f.session).length,0)})
for(const [role,patch] of [['patient',{}],['dentist',{}],['owner',{}],['staff',{userId:'u4',branchId:'b2'}]])test(`${role} ${patch.userId||''} cannot process an unrelated HMO case`,()=>{const f=fixture(),h=submit(f);f.role(role,patch);assert.equal(f.actions.recordHmoOutcome(h.id,response(h)).ok,false);assert.equal(f.actions.followUpHmo(h.id,{commandId:'x'}).ok,false);assert.equal(f.state.hmo[0].status,'Pending')})
test('malformed HMO treatment links cannot change another case or patient',()=>{const f=fixture(),t=complete(f);f.role('staff');const h=f.state.hmo[0];f.patch({hmo:[{...h,patientId:'p2'}]});const before=structuredClone(f.state.hmo);assert.equal(f.actions.provideHmoRequirement(h.id,'valid-id',{fileName:'bad.pdf'}).ok,false);assert.deepEqual(f.state.hmo,before);f.role('patient',{userId:'u13',patientId:'p2'});assert.equal(visibleHmo(f.state,f.session).length,0);assert.equal(f.state.treatments[0].id,t.id)})
test('response cannot target a different case or reuse another case response command',()=>{const f=fixture(),h=submit(f);assert.equal(f.actions.recordHmoOutcome(h.id,{...response(h),caseId:'another'}).ok,false);ok(f.actions.recordHmoOutcome(h.id,response(h)));const a=book(f,{start:'13:00'}),second=submit(f,ready(f,ok(f.actions.createHmoCase({appointmentId:a.id}))),'submit-2');assert.equal(f.actions.recordHmoOutcome(second.id,response(second)).ok,false);assert.equal(f.state.hmo.find(x=>x.id===second.id).status,'Pending')})
test('submission retry after Returned never resubmits the stale request',()=>{const f=fixture(),h=submit(f);ok(f.actions.recordHmoOutcome(h.id,response(h,'Returned')));assert.equal(f.actions.submitHmoCase(h.id,{commandId:'submit-1'}).unchanged,true);assert.equal(f.state.hmo[0].status,'Returned');assert.equal(f.state.hmo[0].submissionCycle,1)})
test('incomplete requirements and final outcomes block impossible transitions',()=>{const f=fixture(),h=create(f);assert.equal(f.actions.submitHmoCase(h.id,{commandId:'x'}).ok,false);assert.equal(f.actions.recordHmoOutcome(h.id,response(h)).ok,false);const pending=submit(f,ready(f,h));ok(f.actions.recordHmoOutcome(h.id,response(pending,'Rejected')));assert.equal(f.actions.provideHmoRequirement(h.id,'valid-id',{fileName:'changed'}).ok,false);assert.equal(f.actions.escalateHmo(h.id).ok,false)})

test('appointment notification is created once and owned by exact patient user',()=>{const f=fixture(),a=ok(f.actions.saveAppointment(form,{commandId:'book'}));const before=f.state.notifications.length;ok(f.actions.saveAppointment(form,{commandId:'book'}));assert.equal(f.state.notifications.length,before);const n=f.state.notifications.find(n=>n.eventType==='appointment.created');assert.equal(n.patientId,'p1');assert.equal(n.recipientUserId,'u12');assert.equal(n.entityId,a.id);assert.ok(f.state.workflowLog.some(e=>e.id===n.eventId))})
test('prescription task notification is assigned only to treating Dentist identity',()=>{const f=fixture();complete(f,{prescriptionRequired:true});const mine=visibleNotifications(f.state,f.session);assert.equal(mine.length,1);assert.equal(mine[0].recipientUserId,'u3');assert.equal(mine[0].dentistId,'d1');f.role('dentist',{userId:'u6',dentistId:'d2'});assert.equal(visibleNotifications(f.state,f.session).length,0)})
test('Staff invoice notifications respect assigned branch and permission',()=>{const f=fixture();complete(f);f.role('staff');assert.ok(visibleNotifications(f.state,f.session).some(n=>n.type==='Invoice review needed'));f.role('staff',{userId:'u4',branchId:'b2'});assert.equal(visibleNotifications(f.state,f.session).length,0)})
test('mark read changes only the exact notification recipient',()=>{const f=fixture(),h=create(f);const n=f.state.notifications.find(n=>n.recipientUserId==='u12');assert.equal(f.actions.markNotificationRead(n.id).ok,false);assert.equal(f.state.notifications.find(x=>x.id===n.id).read,false);f.role('patient');ok(f.actions.markNotificationRead(n.id));assert.ok(f.state.notifications.find(x=>x.id===n.id).readAt);assert.ok(f.state.notifications.filter(x=>x.recipientUserId==='u2').every(n=>!n.read))})
test('mark all read is identity-specific for two Dentists',()=>{const f=fixture();f.patch({notifications:[{id:'d1',recipientUserId:'u3',recipientRole:'dentist',dentistId:'d1',patientId:'p1',read:false},{id:'d2',recipientUserId:'u6',recipientRole:'dentist',dentistId:'d2',patientId:'p2',read:false}]});f.role('dentist');ok(f.actions.markAllNotificationsRead());assert.equal(f.state.notifications[0].read,true);assert.equal(f.state.notifications[1].read,false)})
test('patient mark-all never changes another patient read flags',()=>{const f=fixture();book(f);book(f,{patientId:'p2',start:'13:00'});f.role('patient');ok(f.actions.markAllNotificationsRead());assert.ok(f.state.notifications.filter(n=>n.patientId==='p1').every(n=>n.read));assert.ok(f.state.notifications.filter(n=>n.patientId==='p2').every(n=>!n.read))})
test('notification navigation preserves canonical entity and ignores forged action context',()=>{const f=fixture(),h=create(f);f.role('patient');const n=visibleNotifications(f.state,f.session).find(n=>n.entityType==='hmo');const action=notificationDestination(f.state,f.session,{...n,action:{page:'hmo',context:{hmoCaseId:'wrong',patientId:'p2'}}});assert.equal(action.context.hmoCaseId,h.id);assert.equal(action.context.patientId,'p1');assert.equal(notificationDestination(f.state,f.session,{...n,entityId:'other'}),null)})
test('authorized prescription creates one private patient notification linked to its event',()=>{const f=fixture(),t=complete(f,{prescriptionRequired:true});const input={treatmentId:t.id,items:[{medication:'Private medication',dosage:'Private dose',instructions:'Private instructions'}]};ok(f.actions.authorizePrescription(input));const count=f.state.notifications.length;ok(f.actions.authorizePrescription(input));assert.equal(f.state.notifications.length,count);const n=f.state.notifications.find(n=>n.eventType==='prescription.authorized');assert.equal(n.recipientUserId,'u12');assert.ok(!n.body.includes('Private'));assert.ok(f.state.workflowLog.some(e=>e.id===n.eventId))})
test('invoice and receipt each notify once with exact invoice navigation',()=>{const f=fixture();complete(f);f.role('staff');const i=f.state.invoices[0];ok(f.actions.reviewInvoice(i.id));ok(f.actions.issueInvoice(i.id));ok(f.actions.issueInvoice(i.id));ok(f.actions.postPayment(i.id,'Cash',i.total));ok(f.actions.postPayment(i.id,'Cash',i.total));assert.equal(f.state.notifications.filter(n=>n.eventType==='billing.issue').length,1);assert.equal(f.state.notifications.filter(n=>n.eventType==='billing.payment').length,1);f.role('patient');const n=visibleNotifications(f.state,f.session).find(n=>n.eventType==='billing.payment');assert.equal(notificationDestination(f.state,f.session,n).context.invoiceId,i.id);assert.ok(f.state.workflowLog.some(e=>e.id===n.eventId))})
test('follow-up booking reschedule and cancellation generate distinct related notifications',()=>{const f=fixture();complete(f,{followupRequired:true});f.role('staff');const follow=f.state.followups[0],a=ok(f.actions.saveAppointment({...form,start:'13:00'},{followupId:follow.id}));ok(f.actions.saveAppointment({...form,start:'14:00'},{appointmentId:a.id}));ok(f.actions.cancelAppointment(a.id));for(const type of ['followup.scheduled','followup.rescheduled','followup.cancelled']){const n=f.state.notifications.find(n=>n.eventType===type);assert.ok(n,type);assert.equal(n.entityId,a.id);assert.equal(n.recipientUserId,'u12')}})
test('HMO missing requirement and provider response notifications target correct patient',()=>{const f=fixture(),h=create(f);let n=f.state.notifications.find(n=>n.eventType==='hmo.requirements.missing'&&n.recipientRole==='patient');assert.equal(n.patientId,h.patientId);assert.equal(n.entityId,h.id);const submitted=submit(f,ready(f,h));ok(f.actions.recordHmoOutcome(h.id,response(submitted)));n=f.state.notifications.find(n=>n.eventType==='hmo.provider.response.recorded');assert.equal(n.recipientUserId,'u12');assert.ok(!n.body.includes('Internal'))})
test('legacy patient notifications do not become shared Staff notifications',()=>{const f=fixture({notifications:structuredClone(data.INITIAL_NOTIFICATIONS)});assert.equal(visibleNotifications(f.state,f.session).length,0);f.role('patient');assert.ok(visibleNotifications(f.state,f.session).every(n=>n.patientId==='p1'));f.role('dentist');assert.equal(visibleNotifications(f.state,f.session).length,0)})
test('foreground appointment reminders use clinic time and do not duplicate',()=>{const f=fixture();book(f);ok(f.actions.evaluateOperationalReminders());assert.equal(f.state.notifications.filter(n=>n.eventType==='appointment.reminder').length,1);assert.equal(f.actions.evaluateOperationalReminders().unchanged,true)})
test('significant delay notification is timestamp-based and once per queue encounter',()=>{const f=fixture(),a=book(f);ok(f.actions.checkInAppointment(a.id));instant='2026-09-19T03:00:00Z';ok(f.actions.evaluateOperationalReminders());ok(f.actions.evaluateOperationalReminders());assert.equal(f.state.notifications.filter(n=>n.eventType==='queue.delay').length,1)})

test('message read state is participant-specific and never updates notifications',()=>{const f=fixture();thread(f);book(f);const notifications=structuredClone(f.state.notifications);ok(f.actions.markConversationRead('c1'));assert.deepEqual(f.state.conversations[0].unreadUserIds,['u12','u3']);assert.ok(f.state.conversations[0].readAtByUser.u2);assert.deepEqual(f.state.notifications,notifications)})
test('patient cannot access another patient conversation',()=>{const f=fixture();thread(f);f.role('patient',{userId:'u13',patientId:'p2'});assert.equal(visibleConversations(f.state,f.session).length,0);assert.equal(f.actions.markConversationRead('c1').ok,false);assert.equal(f.actions.replyToConversation('c1','Unauthorized','reply').ok,false)})
test('Dentist role string alone never grants conversation access',()=>{const f=fixture();thread(f,{participantUserIds:['u12','u2'],assignedRole:'Dentist'});f.role('dentist');assert.equal(visibleConversations(f.state,f.session).length,0);assert.equal(f.actions.replyToConversation('c1','Unauthorized','reply').ok,false)})
test('unassigned legacy Dentist conversation is withheld instead of granting role access',()=>{const f=fixture({conversations:[{id:'legacy',patientId:'p1',assignedRole:'Dentist',status:'Open',messages:[]}]});f.role('dentist');assert.equal(visibleConversations(f.state,f.session).length,0);f.role('patient');assert.equal(visibleConversations(f.state,f.session).length,0)})
test('explicit legacy named assignee migrates to actual participant identity',()=>{const f=fixture({conversations:[{id:'legacy',patientId:'p1',assignedTo:'Dr. Miguel Reyes',assignedRole:'Dentist',status:'Open',unreadBy:['dentist'],messages:[]}]});assert.deepEqual(f.state.conversations[0].participantUserIds,['u12','u3']);f.role('dentist');assert.equal(visibleConversations(f.state,f.session).length,1);f.role('dentist',{userId:'u6',dentistId:'d2'});assert.equal(visibleConversations(f.state,f.session).length,0)})
test('Staff participant must also belong to conversation branch',()=>{const f=fixture();thread(f,{participantUserIds:['u12','u4']});f.role('staff',{userId:'u4',branchId:'b2'});assert.equal(visibleConversations(f.state,f.session).length,0);assert.equal(f.actions.replyToConversation('c1','Wrong branch','reply').ok,false)})
test('authorized reply updates exact thread and other participant unread state only',()=>{const f=fixture();thread(f,{unreadUserIds:[]});f.patch({conversations:[...f.state.conversations,{id:'other',patientId:'p2',branchId:'b2',participantUserIds:['u13','u4'],unreadUserIds:[],messages:[],status:'Open'}]});const other=structuredClone(f.state.conversations[1]);ok(f.actions.replyToConversation('c1','Hello patient','reply-1'));assert.equal(f.state.conversations[0].messages[0].senderUserId,'u2');assert.deepEqual(f.state.conversations[0].unreadUserIds,['u12','u3']);assert.deepEqual(f.state.conversations[1],other);assert.equal(f.state.notifications.length,0)})
test('reply retry is idempotent even after thread closes',()=>{const f=fixture();thread(f);ok(f.actions.replyToConversation('c1','Hello','reply'));ok(f.actions.closeConversation('c1'));assert.equal(f.actions.replyToConversation('c1','Hello','reply').unchanged,true);assert.equal(f.state.conversations[0].messages.length,1);assert.equal(f.actions.replyToConversation('c1','Another','reply-2').ok,false)})
test('closing conversation preserves other participant unread flags',()=>{const f=fixture();thread(f);ok(f.actions.closeConversation('c1'));assert.deepEqual(f.state.conversations[0].unreadUserIds,['u12','u2','u3'])})
test('inquiry conversion links appointment and conversation exactly once',()=>{const f=fixture(),a=book(f),i=ok(f.actions.createInquiry({name:'Contact',topic:'Booking',source:'Website'},'inquiry-create'));ok(f.actions.updateInquiry(i.id,'Responded'));const converted=ok(f.actions.convertInquiry(i.id,a.id));assert.equal(converted.bookedAppointmentId,a.id);assert.equal(f.state.conversations[0].inquiryId,i.id);assert.equal(f.state.conversations[0].patientId,a.patientId);assert.deepEqual(f.state.conversations[0].participantUserIds,['u2','u12']);const count=f.state.workflowLog.length;assert.equal(f.actions.convertInquiry(i.id,a.id).unchanged,true);assert.equal(f.state.conversations.length,1);assert.equal(f.state.workflowLog.length,count)})
test('inquiry conversion rejects different assigned branch and duplicate relinking',()=>{const f=fixture(),a=book(f),i=ok(f.actions.createInquiry({name:'Contact',topic:'Booking'},'inquiry'));ok(f.actions.convertInquiry(i.id,a.id));const other=book(f,{start:'13:00'});assert.equal(f.actions.convertInquiry(i.id,other.id).ok,false);f.role('staff',{userId:'u4',branchId:'b2'});assert.equal(f.actions.convertInquiry(i.id,a.id).ok,false)})

test('completion retains one Phase 2 chain alongside HMO and notification orchestration',()=>{const f=fixture(),t=complete(f,{prescriptionRequired:true,followupRequired:true});const before=structuredClone(f.state);ok(f.actions.completeTreatment({queueEntryId:t.queueEntryId}));assert.deepEqual(f.state,before);assert.equal(f.state.invoices.length,1);assert.equal(f.state.followups.length,1);assert.equal(f.state.hmo.length,1);assert.equal(f.state.workflowLog.filter(e=>e.eventType==='clinical.treatment.completed').length,1)})
test('workflow events contain exact entity context actor and timestamp',()=>{const f=fixture(),h=create(f),e=f.state.workflowLog.find(e=>e.eventType==='hmo.requirements.missing');assert.equal(e.entityType,'hmo');assert.equal(e.entityId,h.id);assert.equal(e.appointmentId,h.appointmentId);assert.equal(e.patientId,'p1');assert.equal(e.branchId,'b1');assert.equal(e.actorUserId,'u2');assert.equal(e.createdAt,clinicNow().timestamp)})
test('failed HMO command preserves business state and does not log false Success',()=>{const f=fixture(),h=create(f),before=structuredClone(f.state.hmo),success=f.state.workflowLog.filter(e=>e.status==='Success').length;assert.equal(f.actions.submitHmoCase(h.id,{commandId:'bad'}).ok,false);assert.deepEqual(f.state.hmo,before);assert.equal(f.state.workflowLog.filter(e=>e.status==='Success').length,success);assert.equal(f.state.workflowLog[0].status,'Failed');assert.equal(f.state.workflowLog[0].entityId,h.id)})
test('repeated failure attempt is deduplicated and does not create render-time logs',()=>{const f=fixture(),h=create(f);f.actions.submitHmoCase(h.id,{commandId:'bad'});const before=structuredClone(f.state);f.actions.submitHmoCase(h.id,{commandId:'bad'});assert.deepEqual(f.state,before);automationSnapshot(f.state);visibleHmo(f.state,f.session);visibleNotifications(f.state,f.session);assert.deepEqual(f.state,before)})
test('Automation Monitor reads events and warnings without mutating protected rules',()=>{const f=fixture(),h=submit(f);instant='2026-09-19T15:08:00Z';ok(f.actions.evaluateHmoTimers());const before=structuredClone(f.state);const monitor=automationSnapshot(f.state);assert.equal(monitor.warnings.length,1);assert.equal(monitor.rules.length,6);assert.deepEqual(f.state,before)})
test('failed HMO downstream handoff preserves completed care and records a warning',()=>{const f=fixture(),a=book(f);f.patch({hmo:[{id:'bad',patientId:'p2',appointmentId:a.id,branchId:'b1',providerId:'hmo-healthfirst'}]});const q=ok(f.actions.checkInAppointment(a.id));f.role('dentist');ok(f.actions.updateQueue(q.id,'Called'));ok(f.actions.saveTreatment({queueEntryId:q.id}));const r=f.actions.completeTreatment({queueEntryId:q.id,procedure:'Documented',procedures:[{serviceId:'svc1',quantity:1}]});assert.equal(r.ok,true);assert.ok(r.warnings.length);assert.equal(f.state.treatments[0].status,'Completed');assert.equal(f.state.invoices.length,1);assert.equal(f.state.hmo[0].patientId,'p2');assert.ok(f.state.workflowLog.some(e=>e.eventType==='hmo.handoff.needs_review'&&e.status==='Warning'))})
test('Phase 3 records survive ID-only persistence and normalization without events',()=>{const f=fixture(),h=submit(f);contact(f,h);thread(f);ok(f.actions.replyToConversation('c1','Persist me','reply'));const before=structuredClone(f.state);const patch=Object.fromEntries(['hmo','notifications','conversations','inquiries'].map(k=>[k,JSON.parse(JSON.stringify(persistableCollection(k,f.state[k])))]));f.patch(patch);assert.equal(f.state.hmo[0].providerId,h.providerId);assert.equal(f.state.hmo[0].contacts[0].caseId,h.id);assert.equal(f.state.conversations[0].messages[0].senderUserId,'u2');assert.deepEqual(f.state.workflowLog,before.workflowLog)})

test('missing or future submission timestamps block response processing',()=>{for(const submittedAt of [null,'not-a-date','2099-01-01T12:00:00+08:00']){const f=fixture(),h=submit(f);f.patch({hmo:[{...f.state.hmo[0],submittedAt}]});assert.equal(f.actions.recordHmoOutcome(h.id,response(h)).ok,false);assert.equal(f.state.hmo[0].status,'Pending')}})
test('unknown requirement IDs and malformed requirement rows cannot be processed',()=>{const f=fixture(),h=create(f);assert.equal(f.actions.provideHmoRequirement(h.id,'unknown',{fileName:'x'}).ok,false);f.patch({hmo:[{...f.state.hmo[0],requirements:[null]}]});assert.equal(f.actions.provideHmoRequirement(h.id,'valid-id',{fileName:'x'}).ok,false);f.role('patient');assert.equal(visibleHmo(f.state,f.session)[0].requirements[0].state,'Needs clinic review')})
test('unrelated Staff cannot read patient-uploaded metadata',()=>{const f=fixture(),h=create(f);f.role('staff',{userId:'u4',branchId:'b2'});assert.equal(visibleHmo(f.state,f.session).length,0);assert.equal(f.actions.provideHmoRequirement(h.id,'valid-id',{fileName:'x'}).ok,false)})
test('Staff without HMO permission cannot submit within their branch',()=>{const f=fixture(),h=ready(f);f.patch({users:f.state.users.map(u=>u.id==='u2'?{...u,permissions:['messages']}:u)});assert.equal(f.actions.submitHmoCase(h.id,{commandId:'no-permission',method:'Email',note:'Attempt'}).ok,false)})
test('escalation requires elapsed threshold and a current-cycle contact',()=>{const f=fixture(),h=submit(f);assert.equal(f.actions.escalateHmo(h.id).ok,false);instant='2026-09-19T15:08:00Z';assert.equal(f.actions.escalateHmo(h.id).ok,false);contact(f,h);ok(f.actions.escalateHmo(h.id))})
test('resubmission receives its own single follow-up task while resolving the previous cycle',()=>{const f=fixture(),h=submit(f);instant='2026-09-19T15:08:00Z';ok(f.actions.evaluateHmoTimers());ok(f.actions.recordHmoOutcome(h.id,response(h,'Returned')));ok(f.actions.provideHmoRequirement(h.id,'valid-id',{fileName:'corrected'}));submit(f,f.state.hmo[0],'cycle-2');instant='2026-09-20T04:08:00Z';ok(f.actions.evaluateHmoTimers());ok(f.actions.evaluateHmoTimers());assert.deepEqual(f.state.hmo[0].followUpTasks.map(t=>[t.submissionCycle,t.status]),[[1,'Resolved'],[2,'Open']])})
test('no provider response or approval reference is invented by submission',()=>{const f=fixture(),h=submit(f);assert.equal(h.providerOutcome,null);assert.deepEqual(h.responses,[]);assert.equal(h.reference,undefined);assert.equal(h.approvalNumber,undefined);assert.ok(f.state.notifications.some(n=>n.body.includes('recorded an external submission')))})
test('Dentist coverage projection is encounter-linked and contains no internal logs',()=>{const f=fixture(),h=submit(f);contact(f,h);f.role('dentist');const visible=visibleHmo(f.state,f.session);assert.equal(visible[0].appointmentId,h.appointmentId);assert.equal(visible[0].contacts,undefined);f.role('dentist',{userId:'u6',dentistId:'d2'});assert.equal(visibleHmo(f.state,f.session).length,0)})
test('Patient cannot record metadata for another patient case',()=>{const f=fixture(),h=create(f);f.role('patient',{userId:'u13',patientId:'p2'});assert.equal(f.actions.provideHmoRequirement(h.id,'valid-id',{fileName:'wrong'}).ok,false);assert.equal(f.state.hmo[0].requirements.find(r=>r.ruleId==='valid-id').state,'Missing')})
test('expired session cannot read or mark recipient notification',()=>{const f=fixture();book(f);f.role('patient');f.patch({users:f.state.users.map(u=>u.id==='u12'?{...u,status:'Inactive',accountStatus:'Inactive'}:u)});assert.equal(visibleNotifications(f.state,f.session).length,0);assert.equal(f.actions.markAllNotificationsRead().ok,false)})
test('same-branch Staff mark-all cannot alter another Staff identity',()=>{const f=fixture();f.patch({users:[...f.state.users,{id:'staff-other',roleName:'Receptionist',status:'Active',branchId:'b1',permissions:['hmo']}],notifications:[{id:'mine',recipientUserId:'u2',recipientRole:'staff',branchId:'b1',read:false},{id:'other',recipientUserId:'staff-other',recipientRole:'staff',branchId:'b1',read:false}]});ok(f.actions.markAllNotificationsRead());assert.equal(f.state.notifications[0].read,true);assert.equal(f.state.notifications[1].read,false)})
test('broad Dentist notification role cannot replace recipient identity',()=>{const f=fixture({notifications:[{id:'broad',recipientRole:'dentist',patientId:'p1',dentistId:'d1',read:false}]});f.role('dentist');assert.equal(visibleNotifications(f.state,f.session).length,0)})
test('message reply command cannot be replayed as another participant',()=>{const f=fixture();thread(f);ok(f.actions.replyToConversation('c1','Staff reply','same'));f.role('patient');assert.equal(f.actions.replyToConversation('c1','Patient reply','same').ok,false);assert.equal(f.state.conversations[0].messages.length,1)})
test('Patient cannot close a conversation or access it using forged patientId',()=>{const f=fixture();thread(f);f.role('patient');assert.equal(f.actions.closeConversation('c1').ok,false);f.role('patient',{patientId:'p2'});assert.equal(visibleConversations(f.state,f.session).length,0)})
test('Owner oversight does not grant conversation participation',()=>{const f=fixture();thread(f,{participantUserIds:['u1','u12']});f.role('owner');assert.equal(visibleConversations(f.state,f.session).length,0);assert.equal(f.actions.replyToConversation('c1','Owner reply','owner').ok,false)})
test('legacy ownership ambiguity remains withheld after persistence',()=>{const f=fixture({conversations:[{id:'legacy',patientId:'p1',assignedRole:'Dentist',assignedTo:'Unknown Dentist',status:'Open',messages:[]}]});const persisted=persistableCollection('conversations',f.state.conversations);f.patch({conversations:JSON.parse(JSON.stringify(persisted))});f.role('dentist');assert.equal(visibleConversations(f.state,f.session).length,0)})
test('notification selectors retain full history rather than an eight-record data limit',()=>{const f=fixture();f.patch({notifications:Array.from({length:20},(_,i)=>({id:`n${i}`,recipientUserId:'u12',recipientRole:'patient',patientId:'p1',read:false}))});f.role('patient');assert.equal(visibleNotifications(f.state,f.session).length,20)})
test('legacy static pending hours never survive canonical persistence',()=>{const f=fixture({hmo:structuredClone(data.INITIAL_HMO)});const saved=persistableCollection('hmo',f.state.hmo);assert.ok(saved.every(h=>!Object.hasOwn(h,'pendingHours')));assert.ok(saved.every(h=>h.branchId&&h.providerId))})
test('clinic branch rename cannot change HMO case scope or membership provider',()=>{const f=fixture(),h=create(f);f.patch({branches:f.state.branches.map(b=>b.id==='b1'?{...b,name:'Renamed clinic'}:b)});assert.equal(f.state.hmo[0].branch,'Renamed clinic');assert.equal(f.state.hmo[0].branchId,'b1');assert.equal(f.state.hmo[0].providerId,h.providerId);ok(f.actions.provideHmoRequirement(h.id,'valid-id',{fileName:'id'}))})
test('empty and closed message attempts cannot append messages or notifications',()=>{const f=fixture();thread(f);assert.equal(f.actions.replyToConversation('c1','  ','empty').ok,false);ok(f.actions.closeConversation('c1'));assert.equal(f.actions.replyToConversation('c1','text','closed').ok,false);assert.equal(f.state.conversations[0].messages.length,0);assert.equal(f.state.notifications.length,0)})

test('malformed existing HMO requirement cannot crash a completed treatment handoff',()=>{const f=fixture(),a=book(f),h=ok(f.actions.createHmoCase({appointmentId:a.id}));f.patch({hmo:[{...h,requirements:[null]}]});const q=ok(f.actions.checkInAppointment(a.id));f.role('dentist');ok(f.actions.updateQueue(q.id,'Called'));ok(f.actions.saveTreatment({queueEntryId:q.id}));const result=f.actions.completeTreatment({queueEntryId:q.id,procedure:'Documented',procedures:[{serviceId:'svc1',quantity:1}]});assert.equal(result.ok,true);assert.ok(result.warnings.length);assert.equal(f.state.invoices.length,1)})
test('malformed provider correction list fails without touching a pending case',()=>{const f=fixture(),h=submit(f);assert.equal(f.actions.recordHmoOutcome(h.id,{...response(h,'Returned'),requirementIds:{invalid:true}}).ok,false);assert.equal(f.state.hmo[0].status,'Pending')})
test('historical local eligibility flag is never projected as verified provider approval',()=>{const f=fixture({hmo:structuredClone(data.INITIAL_HMO)});const pending=f.state.hmo.find(h=>h.status==='Pending');assert.equal(pending.eligibility,'Awaiting external provider response');assert.notEqual(pending.eligibility,'Verified')})

test('foreign-case contact records cannot authorize escalation',()=>{const f=fixture(),h=submit(f);instant='2026-09-19T15:08:00Z';f.patch({hmo:[{...f.state.hmo[0],contacts:[{caseId:'another-case',submissionCycle:1,staffUserId:'u2'}]}]});assert.equal(f.actions.escalateHmo(h.id).ok,false);assert.equal(f.state.hmo[0].status,'Pending')})
test('contact command cannot be replayed against another HMO case',()=>{const f=fixture(),h=submit(f);contact(f,h);const a=book(f,{start:'13:00'}),second=submit(f,ready(f,ok(f.actions.createHmoCase({appointmentId:a.id}))),'submit-2');assert.equal(f.actions.followUpHmo(second.id,{commandId:'contact-1',submissionCycle:1,method:'Phone',note:'Wrong case',nextAction:'Wait'}).ok,false);assert.equal(f.state.hmo.find(h=>h.id===second.id).contacts.length,0)})
test('reply command cannot be replayed against another authorized conversation',()=>{const f=fixture();const c=thread(f);f.patch({conversations:[c,{...c,id:'c2'}]});ok(f.actions.replyToConversation('c1','First','reply'));assert.equal(f.actions.replyToConversation('c2','Wrong thread','reply').ok,false);assert.equal(f.state.conversations.find(c=>c.id==='c2').messages.length,0)})

test('HMO views reject inactive accounts and mismatched Dentist identity',()=>{
  const f=fixture();complete(f);f.role('dentist',{userId:'u6',dentistId:'d1'});assert.equal(visibleHmo(f.state,f.session).length,0)
  f.role('patient');f.patch({users:f.state.users.map(u=>u.id==='u12'?{...u,status:'Inactive',accountStatus:'Inactive'}:u)});assert.equal(visibleHmo(f.state,f.session).length,0)
})
test('unresolved legacy assignee labels survive persistence without granting access',()=>{
  const f=fixture({conversations:[{id:'legacy',patientId:'p1',assignedTo:'Unknown person',assignedRole:'Dentist',messages:[]}],inquiries:[{id:'legacy-inquiry',assigned:'Unknown person'}]})
  assert.equal(persistableCollection('conversations',f.state.conversations)[0].assignedTo,'Unknown person')
  assert.equal(persistableCollection('inquiries',f.state.inquiries)[0].assigned,'Unknown person')
  f.role('dentist');assert.equal(visibleConversations(f.state,f.session).length,0)
})
test('malformed legacy document metadata does not imply local completeness',()=>{
  const f=fixture({hmo:[{id:'legacy',patientId:'p1',branchId:'b1',providerId:'hmo-medicare',status:'Draft',documents:{unexpected:true}}]})
  assert.equal(missingRequirements(f.state.hmo[0]).length,3)
})
