import React, { useMemo, useState } from 'react'
import { ROLE_INFO, TODAY } from '../data.js'
import { Button, Card, Field, Modal, Notice, PageHeader, Status, Table, Tabs, Timeline } from '../components.jsx'
import { dateLabel, dentistName, displayTime, patientName, peso, uid } from '../logic.js'

export function BillingPage({ role, store }) {
  const { state, setters, toast, log, workflow }=store
  const pid=ROLE_INFO.patient.patientId
  const visible=state.invoices.filter(i=>role==='patient'?i.patientId===pid:true).sort((a,b)=>b.visitDate.localeCompare(a.visitDate))
  const [createOpen,setCreateOpen]=useState(false)
  const [pay,setPay]=useState(null)
  const unbilled=state.treatments.filter(t=>t.status==='Completed'&&!state.invoices.some(i=>i.treatmentId===t.id))
  const [invoiceForm,setInvoiceForm]=useState({treatmentId:'',patientId:state.patients[0]?.id||'',branch:'Branch A',item:'Dental Service',amount:1000})
  const createInvoice=()=>{
    const amount=Number(invoiceForm.amount||0); if(amount<=0)return toast('Enter a valid charge amount.','warning')
    const inv={id:uid('inv'),treatmentId:invoiceForm.treatmentId||null,patientId:invoiceForm.patientId,visitDate:TODAY,branch:invoiceForm.branch,items:[{name:invoiceForm.item,amount}],total:amount,status:'Pending',method:'—',paidAt:null,receipt:null}
    setters.setInvoices(xs=>[inv,...xs]);workflow('M11','Patient bill generated',`${patientName(inv.patientId,state.patients)} • ${peso.format(amount)}`);log(ROLE_INFO.staff.name,'Generated patient bill','M11');toast('Patient bill generated.','success');setCreateOpen(false)
  }
  const postPayment=(method)=>{
    if(!pay)return
    const receipt=`OR-2026-${String(Date.now()).slice(-6)}`
    setters.setInvoices(xs=>xs.map(i=>i.id===pay.id?{...i,status:'Paid',method,paidAt:'2026-09-19 10:08',receipt}:i))
    workflow('M11','Payment posted',`${patientName(pay.patientId,state.patients)} • ${peso.format(pay.total)}`);log(ROLE_INFO.staff.name,'Posted payment and generated receipt','M11');toast('Payment validated, receipt generated, and transaction closed.','success');setPay(null)
  }
  return <>
    <PageHeader title={role==='patient'?'Bills & Receipts':'Billing & Payment Management'} text={role==='patient'?'Private view of only your own bills and official/digital receipt records.':'Staff billing view for treatment charges, payment posting, receipt generation, and transaction closure.'} modules={[11]}/>
    {role==='staff'&&<Card title="Billing actions" actions={<Button onClick={()=>setCreateOpen(true)}>Generate patient bill</Button>}><Notice tone="info">In production, billable charges would be prepared from completed treatment records and clinic configuration. This frontend shows the intended workflow without a backend.</Notice></Card>}
    <Card className={role==='staff'?'top-gap':''} title={role==='patient'?'My transactions':'Transactions'}>
      <Table rows={visible} columns={[
        {key:'date',label:'Visit date',render:i=>dateLabel(i.visitDate)},...(role==='staff'?[{key:'patient',label:'Patient',render:i=>patientName(i.patientId,state.patients)}]:[]),
        {key:'items',label:'Charges',render:i=><div>{i.items.map((x,idx)=><div key={idx}><b>{x.name}</b><small className="block-muted">{peso.format(x.amount)}</small></div>)}</div>},
        {key:'branch',label:'Branch'},{key:'total',label:'Total',render:i=><b>{peso.format(i.total)}</b>},{key:'status',label:'Status',render:i=><Status>{i.status}</Status>},{key:'method',label:'Payment method'},
        {key:'receipt',label:'Receipt',render:i=>i.receipt||'—'},...(role==='staff'?[{key:'action',label:'Action',render:i=>i.status==='Pending'?<Button size="sm" onClick={()=>setPay(i)}>Post payment</Button>:null}]:[])
      ]}/>
    </Card>
    <Modal open={createOpen} onClose={()=>setCreateOpen(false)} title="Generate patient bill" subtitle="Receive completed treatment, review applicable charges, then generate the patient bill."><div className="form-grid"><Field label="Completed treatment"><select value={invoiceForm.treatmentId} onChange={e=>{const t=state.treatments.find(x=>x.id===e.target.value);const p=t?state.patients.find(x=>x.id===t.patientId):null;setInvoiceForm({...invoiceForm,treatmentId:e.target.value,patientId:t?.patientId||invoiceForm.patientId,branch:p?.preferredBranch||invoiceForm.branch,item:t?.procedure||t?.plan||invoiceForm.item})}}><option value="">Manual / legacy charge</option>{unbilled.map(t=><option key={t.id} value={t.id}>{patientName(t.patientId,state.patients)} • {t.procedure||t.plan} • {dateLabel(t.date)}</option>)}</select></Field><Field label="Patient"><select value={invoiceForm.patientId} onChange={e=>setInvoiceForm({...invoiceForm,patientId:e.target.value})}>{state.patients.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Branch"><select value={invoiceForm.branch} onChange={e=>setInvoiceForm({...invoiceForm,branch:e.target.value})}>{state.branches.map(b=><option key={b.id}>{b.name}</option>)}</select></Field><Field label="Applicable charge"><input value={invoiceForm.item} onChange={e=>setInvoiceForm({...invoiceForm,item:e.target.value})}/></Field><Field label="Reviewed amount"><input type="number" min="1" value={invoiceForm.amount} onChange={e=>setInvoiceForm({...invoiceForm,amount:e.target.value})}/></Field><Notice tone="info">This is the frontend review step for applicable charges. A backend would load configured service charges and protect transaction integrity.</Notice><Button className="span-2" onClick={createInvoice}>Generate Patient Bill</Button></div></Modal>
    <Modal open={!!pay} onClose={()=>setPay(null)} title="Record payment" subtitle={pay?`${patientName(pay.patientId,state.patients)} • ${peso.format(pay.total)}`:''}><div className="payment-options"><Button onClick={()=>postPayment('Cash')}>Cash</Button><Button onClick={()=>postPayment('GCash')}>GCash</Button><Button onClick={()=>postPayment('Card')}>Card</Button><Button onClick={()=>postPayment('Bank Transfer')}>Bank Transfer</Button></div></Modal>
  </>
}

export function HmoPage({ role, activeBranch, store }) {
  const { state, setters, toast, log, workflow, notify }=store
  const [selected,setSelected]=useState(null)
  const [outcome,setOutcome]=useState('Approved')
  const [createOpen,setCreateOpen]=useState(false)
  const [caseForm,setCaseForm]=useState({patientId:state.patients[0]?.id||'',provider:'',memberId:'',treatment:'',branch:'Branch A'})
  const visible=state.hmo.filter(h=>activeBranch==='All Branches'||h.branch===activeBranch)
  const createCase=()=>{if(!caseForm.provider||!caseForm.memberId||!caseForm.treatment)return toast('Provider, member ID, and requested treatment are required.','warning');const h={id:uid('h'),...caseForm,eligibility:'Unchecked',documents:[],missing:['Eligibility check','Required HMO documents'],status:'Draft',submittedAt:null,pendingHours:0,reference:null,followUpCount:0,lastContact:null,providerOutcome:null};setters.setHmo(xs=>[h,...xs]);log(ROLE_INFO.staff.name,'Created HMO verification case','M12');toast('HMO case created. Eligibility and documents must be verified before submission.','success');setCreateOpen(false)}
  const verifyEligibility=h=>{setters.setHmo(xs=>xs.map(x=>x.id===h.id?{...x,eligibility:'Verified',missing:x.missing.filter(m=>m!=='Eligibility check'),status:x.missing.filter(m=>m!=='Eligibility check').length?'Missing Requirements':'Verified'}:x));log(ROLE_INFO.staff.name,'Verified HMO eligibility','M12');toast('Eligibility marked verified.','success')}
  const completeDocs=h=>{setters.setHmo(xs=>xs.map(x=>x.id===h.id?{...x,missing:[],documents:[...new Set([...x.documents,'Valid ID','Dentist treatment request'])],status:'Verified'}:x));log(ROLE_INFO.staff.name,'Completed HMO document verification','M12');toast('Missing HMO requirements cleared and case marked verified.','success')}
  const submit=h=>{if(h.missing.length)return toast('Missing HMO requirements must be cleared before submission.','warning');const ref=h.reference||`HMO-2026-${String(Date.now()).slice(-6)}`;setters.setHmo(xs=>xs.map(x=>x.id===h.id?{...x,status:'Pending',submittedAt:'2026-09-19 10:08',pendingHours:0,reference:ref}:x));workflow('M13','HMO request submitted',`${ref} • pending timer started`);toast('HMO request submitted, status set to pending, and timer started.','success')}
  const followUp=h=>{setters.setHmo(xs=>xs.map(x=>x.id===h.id?{...x,followUpCount:x.followUpCount+1,lastContact:'2026-09-19 10:08'}:x));workflow('M14','HMO follow-up action recorded',`${h.reference||h.id} • attempt ${h.followUpCount+1}`);log(ROLE_INFO.staff.name,'Recorded HMO provider contact attempt','M14');toast('Follow-up attempt recorded and pending timer continues.','success')}
  const escalate=h=>{setters.setHmo(xs=>xs.map(x=>x.id===h.id?{...x,status:'Escalated',lastContact:'2026-09-19 10:08'}:x));notify(h.patientId,'HMO Escalation Update',`Your HMO case has been escalated for additional clinic follow-up with ${h.provider}.`);workflow('M14','Unresolved HMO case escalated',h.reference||h.id);log(ROLE_INFO.staff.name,'Escalated unresolved HMO case','M14');toast('Unresolved HMO case escalated and status notification generated.','success')}
  const recordOutcome=()=>{if(!selected)return;setters.setHmo(xs=>xs.map(x=>x.id===selected.id?{...x,status:outcome==='Returned'?'Returned':outcome,providerOutcome:outcome,pendingHours:0,lastContact:'2026-09-19 10:08'}:x));notify(selected.patientId,'HMO Status Update',`Your HMO case status is now ${outcome}.`);workflow('M13',`Provider response recorded: ${outcome}`,selected.reference||selected.id);log(ROLE_INFO.staff.name,'Recorded HMO provider response','M13');toast('Provider response recorded. Clinic staff did not generate the approval; they recorded the provider outcome.','success');setSelected(null)}
  return <>
    <PageHeader title={role==='owner'?'HMO Overview':'HMO Verification, Request & Follow-Up'} text={role==='owner'?'Read-only management oversight of HMO verification, pending duration, provider outcomes, and escalation status.':'Verify requirements, submit complete cases, track pending timers, record provider responses, and perform timer-driven follow-up.'} modules={[12,13,14]}/>
    {role==='staff'&&<div className="page-toolbar"><Button onClick={()=>setCreateOpen(true)}>Create HMO Case</Button></div>}
    <div className="stats-grid small"><StatCardMini label="Missing requirements" value={visible.filter(h=>h.missing.length).length}/><StatCardMini label="Pending" value={visible.filter(h=>h.status==='Pending').length}/><StatCardMini label="Past 12h threshold" value={visible.filter(h=>h.status==='Pending'&&h.pendingHours>=12).length}/><StatCardMini label="Approved" value={visible.filter(h=>h.status==='Approved').length}/></div>
    <Card title="HMO cases" subtitle={role==='owner'?'Owner/Admin can monitor but does not approve HMO cases.':'Approval/rejection/return is recorded only after the HMO provider responds.'}>
      <Table rows={visible} columns={[
        {key:'patient',label:'Patient',render:h=>patientName(h.patientId,state.patients)},{key:'provider',label:'Provider'},{key:'memberId',label:'Member ID'},{key:'treatment',label:'Treatment'},{key:'branch',label:'Branch'},
        {key:'docs',label:'Requirements',render:h=>h.missing.length?<span className="danger-text">{h.missing.length} missing</span>:<span className="success-text">Complete</span>},
        {key:'pending',label:'Pending time',render:h=>h.status==='Pending'?`${h.pendingHours}h`:'—'},{key:'status',label:'Status',render:h=><Status>{h.status}</Status>},
        {key:'action',label:'Actions',render:h=>role==='staff'?<div className="row-actions">{h.eligibility!=='Verified'&&<Button size="sm" variant="ghost" onClick={()=>verifyEligibility(h)}>Verify eligibility</Button>}{h.eligibility==='Verified'&&h.missing.length>0&&<Button size="sm" variant="ghost" onClick={()=>completeDocs(h)}>Complete docs</Button>}{h.eligibility==='Verified'&&!h.missing.length&&!h.submittedAt&&<Button size="sm" onClick={()=>submit(h)}>Submit</Button>}{h.status==='Pending'&&<><Button size="sm" variant="ghost" onClick={()=>followUp(h)}>Log follow-up</Button>{h.pendingHours>=12&&h.followUpCount>0&&<Button size="sm" variant="danger" onClick={()=>escalate(h)}>Escalate</Button>}<Button size="sm" onClick={()=>setSelected(h)}>Record provider response</Button></>}</div>:<Button size="sm" variant="ghost" onClick={()=>setSelected(h)}>View</Button>}
      ]}/>
    </Card>
    <Modal open={createOpen} onClose={()=>setCreateOpen(false)} title="Create HMO verification case" subtitle="Begin with patient/provider details before eligibility and document validation."><div className="form-grid"><Field label="Patient"><select value={caseForm.patientId} onChange={e=>setCaseForm({...caseForm,patientId:e.target.value})}>{state.patients.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Branch"><select value={caseForm.branch} onChange={e=>setCaseForm({...caseForm,branch:e.target.value})}>{state.branches.map(b=><option key={b.id}>{b.name}</option>)}</select></Field><Field label="HMO provider"><input value={caseForm.provider} onChange={e=>setCaseForm({...caseForm,provider:e.target.value})}/></Field><Field label="Member ID"><input value={caseForm.memberId} onChange={e=>setCaseForm({...caseForm,memberId:e.target.value})}/></Field><Field label="Requested treatment"><input value={caseForm.treatment} onChange={e=>setCaseForm({...caseForm,treatment:e.target.value})}/></Field><Button onClick={createCase}>Create HMO Case</Button></div></Modal>
    <Modal open={!!selected} onClose={()=>setSelected(null)} title={role==='owner'?'HMO case detail':'Record HMO provider response'} subtitle={selected?.reference||selected?.id}>
      {selected&&<div><div className="detail-list"><div><span>Patient</span><b>{patientName(selected.patientId,state.patients)}</b></div><div><span>Provider</span><b>{selected.provider}</b></div><div><span>Status</span><Status>{selected.status}</Status></div><div><span>Submitted</span><b>{selected.submittedAt||'Not submitted'}</b></div><div><span>Follow-up attempts</span><b>{selected.followUpCount}</b></div><div><span>Last contact</span><b>{selected.lastContact||'—'}</b></div></div>{role==='staff'&&selected.status==='Pending'&&<><Field label="Provider response"><select value={outcome} onChange={e=>setOutcome(e.target.value)}><option>Approved</option><option>Rejected</option><option>Returned</option></select></Field><Button className="full" onClick={recordOutcome}>Record Provider Outcome</Button><Notice tone="info">This button records an external HMO provider response. It does not let clinic staff approve their own HMO request.</Notice></>}</div>}
    </Modal>
  </>
}
function StatCardMini({label,value}){return <div className="mini-stat"><span>{label}</span><b>{value}</b></div>}

export function InquiriesPage({ store }) {
  const { state, setters, toast, log }=store
  const [newInquiry,setNewInquiry]=useState({source:'Facebook',name:'',contact:'',topic:''})
  const [linking,setLinking]=useState(null)
  const [appointmentId,setAppointmentId]=useState('')
  const add=()=>{if(!newInquiry.name||!newInquiry.topic)return toast('Enter the contact name and inquiry topic.','warning');const i={id:uid('inq'),...newInquiry,status:'Open',assigned:'Alyssa Cruz',receivedAt:'2026-09-19 10:08',respondedAt:null,bookedAppointmentId:null};setters.setInquiries(xs=>[i,...xs]);log('System','Captured and assigned new social inquiry','M16');toast('Inquiry captured and assigned to responsible staff.','success');setNewInquiry({source:'Facebook',name:'',contact:'',topic:''})}
  const respond=i=>{setters.setInquiries(xs=>xs.map(x=>x.id===i.id?{...x,status:'Responded',respondedAt:'2026-09-19 10:08'}:x));log(ROLE_INFO.staff.name,'Recorded staff response to social inquiry','M16');toast('Staff response recorded.','success')}
  const close=i=>{setters.setInquiries(xs=>xs.map(x=>x.id===i.id?{...x,status:'Closed'}:x));toast('Inquiry closed.','success')}
  const linkBooking=()=>{if(!linking||!appointmentId)return toast('Select a booked appointment to link.','warning');setters.setInquiries(xs=>xs.map(x=>x.id===linking.id?{...x,status:'Converted',bookedAppointmentId:appointmentId}:x));log(ROLE_INFO.staff.name,'Converted social inquiry to appointment record','M16');toast('Inquiry linked to a booked appointment and marked converted.','success');setLinking(null);setAppointmentId('')}
  return <>
    <PageHeader title="Social Media Inquiry Management" text="Pre-booking social inquiries become trackable records with source, topic, assignment, response status, follow-up, and conversion to a booked appointment." modules={[16]}/>
    <div className="grid-2">
      <Card title="Capture inquiry"><div className="form-grid"><Field label="Source"><select value={newInquiry.source} onChange={e=>setNewInquiry({...newInquiry,source:e.target.value})}><option>Facebook</option><option>Instagram</option><option>Website</option></select></Field><Field label="Name"><input value={newInquiry.name} onChange={e=>setNewInquiry({...newInquiry,name:e.target.value})}/></Field><Field label="Contact"><input value={newInquiry.contact} onChange={e=>setNewInquiry({...newInquiry,contact:e.target.value})}/></Field><Field label="Topic"><input value={newInquiry.topic} onChange={e=>setNewInquiry({...newInquiry,topic:e.target.value})}/></Field><Button className="span-2" onClick={add}>Create & Assign Inquiry</Button></div></Card>
      <Card title="Response automation"><Notice tone="info">Unanswered inquiries remain visible to staff and would generate reminder tasks after the configured response period in a real implementation.</Notice><div className="metric-row"><div><span>Open inquiries</span><small>Awaiting staff action</small></div><b>{state.inquiries.filter(i=>i.status==='Open').length}</b></div><div className="metric-row"><div><span>Converted to appointment</span><small>Booked inquiries linked to scheduling</small></div><b>{state.inquiries.filter(i=>i.bookedAppointmentId).length}</b></div></Card>
    </div>
    <Card className="top-gap" title="Inquiry worklist"><Table rows={state.inquiries} columns={[{key:'source',label:'Source'},{key:'name',label:'Contact'},{key:'topic',label:'Topic'},{key:'assigned',label:'Assigned staff'},{key:'receivedAt',label:'Received'},{key:'booking',label:'Appointment',render:i=>i.bookedAppointmentId||'—'},{key:'status',label:'Status',render:i=><Status>{i.status}</Status>},{key:'actions',label:'Actions',render:i=><div className="row-actions">{i.status==='Open'&&<Button size="sm" onClick={()=>respond(i)}>Record response</Button>}{['Responded','Open'].includes(i.status)&&!i.bookedAppointmentId&&<Button size="sm" variant="ghost" onClick={()=>setLinking(i)}>Link booked appointment</Button>}{!['Closed','Converted'].includes(i.status)&&<Button size="sm" variant="ghost" onClick={()=>close(i)}>Close</Button>}</div>}]} /></Card>
    <Modal open={!!linking} onClose={()=>setLinking(null)} title="Convert inquiry to appointment" subtitle="Link the social inquiry to the booking that resulted from the conversation."><Field label="Booked appointment"><select value={appointmentId} onChange={e=>setAppointmentId(e.target.value)}><option value="">Select appointment</option>{state.appointments.filter(a=>a.status!=='Cancelled').map(a=><option key={a.id} value={a.id}>{dateLabel(a.date)} • {displayTime(a.start)} • {patientName(a.patientId,state.patients)} • {a.service}</option>)}</select></Field><Button className="full" onClick={linkBooking}>Record Appointment Conversion</Button></Modal>
  </>
}

export function MessagesPage({ role, store }) {
  const { state, setters, toast, log, workflow }=store
  const pid=ROLE_INFO.patient.patientId
  const name=role==='patient'?ROLE_INFO.patient.name:role==='dentist'?ROLE_INFO.dentist.name:ROLE_INFO.staff.name
  const relevant=state.conversations.filter(c=>role==='patient'?c.patientId===pid:role==='dentist'?c.assignedRole==='Dentist':c.assignedRole!=='Dentist')
  const [selected,setSelected]=useState(relevant[0]?.id||null)
  const [text,setText]=useState('')
  const convo=state.conversations.find(c=>c.id===selected)
  const send=()=>{if(!convo||!text.trim())return;const sender=role==='patient'?'patient':role==='dentist'?'dentist':'staff';setters.setConversations(xs=>xs.map(c=>c.id===convo.id?{...c,messages:[...c.messages,{id:uid('cm'),sender,text:text.trim(),at:'2026-09-19 10:08'}],unreadBy:role==='patient'?['staff']:['patient']}:c));log(name,'Sent message in unified conversation','M17');setText('');toast('Message added to the unified conversation history.','success')}
  const resolve=()=>{if(!convo)return;setters.setConversations(xs=>xs.map(c=>c.id===convo.id?{...c,status:'Closed',unreadBy:[]}:c));log(name,'Closed resolved patient conversation','M17');toast('Conversation marked resolved and closed.','success')}
  const retryNotification=n=>{setters.setNotifications(xs=>xs.map(x=>x.id===n.id?{...x,status:'Delivered',createdAt:'2026-09-19 10:08'}:x));workflow('M18','Failed notification retried',`${n.type} delivered via ${n.channel}`);log(ROLE_INFO.staff.name,'Retried failed patient notification','M18');toast('Failed notification retried and delivery status updated.','success')}
  return <>
    <PageHeader title={role==='patient'?'Messages & Updates':'Unified Patient Messaging'} text={role==='patient'?'Two-way clinic conversations plus system-generated operational updates.':'Ongoing identified-patient conversations remain separate from social inquiries and system-generated notifications.'} modules={[17,18]}/>
    <div className="messages-layout">
      <Card className="conversation-list" title="Conversations">{relevant.map(c=><button key={c.id} className={selected===c.id?'selected':''} onClick={()=>setSelected(c.id)}><div><b>{patientName(c.patientId,state.patients)}</b><small>{c.context}</small></div><Status>{c.status}</Status></button>)}</Card>
      <Card className="conversation-card" title={convo?`${patientName(convo.patientId,state.patients)} • ${convo.context}`:'Select a conversation'} actions={convo&&role!=='patient'&&convo.status!=='Closed'?<Button size="sm" variant="ghost" onClick={resolve}>Mark resolved</Button>:null}>{convo?<><div className="message-thread">{convo.messages.map(m=><div className={`bubble ${m.sender===role?'mine':m.sender==='patient'&&role==='patient'?'mine':''}`} key={m.id}><small>{m.sender}</small><p>{m.text}</p><span>{m.at}</span></div>)}</div>{convo.status!=='Closed'?<div className="compose-row"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Write a message..."/><Button onClick={send}>Send</Button></div>:<Notice tone="info">This conversation is resolved and closed. Reopen controls would be permission-based in the backend implementation.</Notice>}</>:<Notice>Select a conversation.</Notice>}</Card>
      <Card className="notification-panel" title="Operational notifications" subtitle="System-generated outbound updates • Module 18">{state.notifications.filter(n=>role==='patient'?n.patientId===pid:true).slice(0,8).map(n=><div className="notification-item" key={n.id}><div><b>{n.type}</b><p>{n.text}</p><small>{n.createdAt} • {n.channel}</small></div><div className="notification-actions"><Status>{n.status}</Status>{role==='staff'&&n.status==='Failed'&&<Button size="sm" variant="ghost" onClick={()=>retryNotification(n)}>Retry</Button>}</div></div>)}</Card>
    </div>
  </>
}
