import React, { useState } from 'react'
import { Icon } from '../components.jsx'
import { clinic } from '../clinic-config.js'
import { PublicHeader, PublicFooter } from './PublicChrome.jsx'

function Actions({light=false}) {
  return <div className={`site-actions ${light?'is-light':''}`}><a className="site-button" href="#create-account">Create Patient Account <Icon name="arrow" size={18}/></a><a className="site-button secondary" href="#sign-in">Sign In</a></div>
}

function PreviewFrame({children,compact=false}) {
  return <div className={`portal-preview ${compact?'compact':''}`}><div className="preview-browser"><span aria-hidden="true"><i/><i/><i/></span><span>Patient Portal</span><Icon name="shield" size={14}/></div>{children}</div>
}

function AppointmentPreview() {
  return <div className="preview-appointment"><div className="preview-calendar"><Icon name="calendar" size={30}/><span>Your visit</span></div><div><small>UPCOMING APPOINTMENT</small><h4>Dental consultation</h4><p>View your confirmed date, time, and clinic details.</p><span className="preview-tag">Appointment details</span></div></div>
}

function HeroPreview() {
  return <figure className="site-hero-visual"><div className="hero-preview-backdrop"/><PreviewFrame>
    <div className="preview-dashboard"><div className="preview-side" aria-hidden="true"><img src={clinic.logo} alt="" width="36" height="36"/>{['home','calendar','receipt','user'].map((icon,i)=><span className={i===0?'active':''} key={icon}><Icon name={icon} size={18}/></span>)}</div>
    <div className="preview-dashboard-main"><div className="preview-greeting"><div><small>YOUR PATIENT PORTAL</small><h3>A clearer view of your care.</h3></div><span className="preview-avatar"><Icon name="user" size={18}/></span></div>
      <AppointmentPreview/>
      <div className="preview-mini-grid"><div><Icon name="receipt"/><b>Receipts & payments</b><span>Your financial history</span></div><div><Icon name="file"/><b>Documents & consent</b><span>Your records in one place</span></div></div>
      <div className="preview-update"><span><Icon name="message" size={19}/></span><div><b>Stay connected with the clinic</b><p>Find messages and updates in your portal.</p></div></div>
    </div></div>
  </PreviewFrame><figcaption>Illustrative preview · no Patient information shown</figcaption></figure>
}

const features=[
  ['calendar','Appointments','Plan your next visit','Find available appointment options and keep track of your scheduled visits.'],
  ['user','Patient information','Keep your details together','View the Patient information available to your account and keep contact details organized.'],
  ['receipt','Billing & receipts','Understand your visit’s billing','Review your invoices, recorded payments, and receipts in one place.'],
  ['file','Documents & consents','Know what’s on file','Access your documents and consent records through your Patient profile.'],
  ['shield','HMO information','Follow your coverage request','See applicable HMO case details, requirements, and recorded coverage information.'],
  ['message','Clinic communication','Keep the conversation connected','Find clinic messages and account updates alongside your other Patient information.'],
]
const previewTabs=[['visits','Appointments'],['records','Documents & HMO'],['billing','Billing & receipts']]

export function PublicSite() {
  const [preview,setPreview]=useState('visits')
  return <div className="public-site"><PublicHeader/><main id="public-main" tabIndex={-1}>
    <section id="home" className="site-hero"><div className="site-container site-hero-grid"><div className="site-hero-copy"><span className="site-eyebrow">{clinic.city} · Patient Portal</span><h1>Care that connects.<br/><em>Even between visits.</em></h1><p>A simpler way to stay connected with {clinic.name}. Manage appointments, find your records, and follow clinic updates in one place.</p><Actions/><a className="site-text-link" href="#portal">Take a look inside your portal <Icon name="arrow" size={17}/></a><div className="site-hero-note"><Icon name="shield" size={17}/><span>Email-verified accounts. Access to your own information.</span></div></div><HeroPreview/></div></section>
    <div className="site-capability-strip"><div className="site-container">{[['calendar','Appointments'],['file','Patient records'],['receipt','Billing & receipts'],['message','Clinic communication']].map(([icon,label])=><span key={label}><Icon name={icon}/>{label}</span>)}</div></div>

    <section id="about" className="site-section"><div className="site-container site-about-grid"><div className="site-about-visual"><span className="site-eyebrow">Your clinic, connected</span><div className="about-clinic-mark"><img src={clinic.logo} alt="" width="80" height="80"/><h3>{clinic.nameLine}<span>{clinic.subtitle}</span></h3><p>{clinic.city}</p></div><div className="about-connected"><span><Icon name="calendar"/>Your visits</span><span><Icon name="file"/>Your information</span><span><Icon name="message"/>Your conversations</span></div></div><div className="site-section-copy"><span className="site-eyebrow">About the clinic portal</span><h2>A familiar clinic.<br/>A more connected experience.</h2><p>{clinic.name} brings appointments, relevant Patient information, billing, documents, and communication together through a single digital portal.</p><p>Find the details you need before your visit and return to the information available to you afterward. The clinic remains your point of contact for questions about your care.</p><a className="site-text-link" href="#contact">Get in touch with the clinic <Icon name="arrow" size={17}/></a></div></div></section>

    <section id="features" className="site-section site-features"><div className="site-container"><div className="site-section-heading"><div><span className="site-eyebrow">Made for your clinic experience</span><h2>Less searching.<br/>More clarity.</h2></div><p>From planning a visit to finding a receipt, your Patient Portal keeps everyday clinic tasks within reach.</p></div><div className="site-feature-grid">{features.map(([icon,label,title,copy],i)=><article className={`site-feature feature-${i}`} key={label}><span className="site-feature-icon"><Icon name={icon} size={25}/></span><span className="site-feature-label">{label}</span><h3>{title}</h3><p>{copy}</p>{i===0&&<div className="feature-visit-visual" aria-hidden="true"><span>Plan</span><i/><span>Confirm</span><i/><span>Visit</span></div>}{i===2&&<div className="feature-receipt-visual" aria-hidden="true"><Icon name="receipt"/><span>Invoice → Payment → Receipt</span></div>}</article>)}</div></div></section>

    <section id="portal" className="site-section site-product"><div className="site-container site-product-grid"><div className="site-section-copy"><span className="site-eyebrow">Inside your Patient Portal</span><h2>The details that matter,<br/>all together.</h2><p>A clear view of your appointments and the information available to your account. Explore a preview of the portal below.</p><div role="tablist" aria-label="Patient portal preview" className="site-preview-tabs">{previewTabs.map(([id,label])=><button key={id} id={`tab-${id}`} type="button" role="tab" aria-selected={preview===id} aria-controls="portal-preview-panel" tabIndex={preview===id?0:-1} onKeyDown={event=>{if(['ArrowDown','ArrowRight','ArrowUp','ArrowLeft'].includes(event.key)){event.preventDefault();const delta=['ArrowDown','ArrowRight'].includes(event.key)?1:-1;const next=previewTabs[(previewTabs.findIndex(x=>x[0]===id)+delta+previewTabs.length)%previewTabs.length][0];setPreview(next);document.getElementById(`tab-${next}`)?.focus()}}} onClick={()=>setPreview(id)}><span>{label}</span><Icon name="arrow" size={17}/></button>)}</div><a href="#create-account" className="site-text-link">Create your Patient account <Icon name="arrow" size={17}/></a></div>
      <div className="site-product-visual" role="tabpanel" id="portal-preview-panel" aria-labelledby={`tab-${preview}`} tabIndex={0}><PreviewFrame compact><div className="product-preview-body"><span className="site-eyebrow">Illustrative portal preview</span>{preview==='visits'?<><h3>Your visits, at a glance.</h3><AppointmentPreview/><div className="preview-list-row"><Icon name="calendar"/><div><b>Appointment history</b><p>Return to details from previous visits.</p></div></div><div className="preview-list-row"><Icon name="bell"/><div><b>Clinic updates</b><p>See updates relevant to your account.</p></div></div></>:preview==='records'?<><h3>Your information, organized.</h3>{[['file','Documents','Find documents you have shared with the clinic.'],['checkin','Consents & agreements','Review consent records on file.'],['shield','HMO coverage','Follow case status and requirements.']].map(([icon,title,copy])=><div className="preview-list-row" key={title}><Icon name={icon}/><div><b>{title}</b><p>{copy}</p></div></div>)}</>:<><h3>A clear record of your billing.</h3><div className="preview-billing-summary"><Icon name="wallet" size={28}/><div><b>Receipts & Payments</b><p>Review your Patient responsibility and recorded payment history.</p></div></div><div className="preview-list-row"><Icon name="receipt"/><div><b>Invoices</b><p>Visit charges and applicable coverage.</p></div></div><div className="preview-list-row"><Icon name="checkin"/><div><b>Receipts</b><p>Evidence of your recorded payments.</p></div></div></>}<p className="preview-disclaimer">Preview only. Your portal shows information linked to your account.</p></div></PreviewFrame></div></div></section>

    <section className="site-section site-how"><div className="site-container"><div className="site-centered-heading"><span className="site-eyebrow">Getting started</span><h2>A few simple steps.<br/>A more connected visit.</h2></div><ol className="site-steps">{[['Create your account','Enter your details and an email address you can access.'],['Verify your email','Use the verification code sent to your email address.'],['Enter your portal','Sign in to the information available to your account.'],['Manage your visits','Explore appointment options and stay in touch with the clinic.']].map(([title,copy],i)=><li key={title}><span className="site-step-number">0{i+1}</span><h3>{title}</h3><p>{copy}</p></li>)}</ol></div></section>

    <section className="site-section site-trust"><div className="site-container site-trust-grid"><div><span className="site-eyebrow">A considered approach to access</span><h2>Your account.<br/>Your Patient information.</h2><p>Simple to use, with account checks built into the way you enter the portal.</p></div><div className="site-trust-points">{[['shield','Email verification','Your email must be verified before normal Patient Portal access.'],['user','Patient-specific access','Sign in to view information linked to your own Patient account.'],['message','Connected with your clinic','Appointments, billing, documents, and messages share one portal.']].map(([icon,title,copy])=><article key={title}><Icon name={icon} size={24}/><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></div></section>

    <section className="site-cta"><div className="site-container"><div><span className="site-eyebrow">Your next step</span><h2>Ready to manage your<br/>dental visits online?</h2><p>Your Patient Portal starts with a verified email and your own account.</p></div><Actions light/></div></section>

    <section id="contact" className="site-section site-contact"><div className="site-container"><div className="site-section-heading"><div><span className="site-eyebrow">Contact</span><h2>Let’s stay connected.</h2></div><p>For questions about the clinic or help with your Patient Portal, get in touch directly.</p></div><div className="site-contact-grid"><div className="site-contact-clinic"><span className="site-contact-icon"><Icon name="building" size={28}/></span><h3>{clinic.name}</h3><p>{clinic.city}</p><span className="site-location-label">{clinic.locationLabel}</span></div><a className="site-contact-method" href={`tel:${clinic.phoneE164}`}><span className="site-eyebrow">Call the clinic</span><strong>{clinic.phoneDisplay}</strong><span>Start a phone call <Icon name="arrow" size={18}/></span></a><a className="site-contact-method" href={`mailto:${clinic.email}`}><span className="site-eyebrow">Email the clinic</span><strong>{clinic.email}</strong><span>Write an email <Icon name="arrow" size={18}/></span></a></div></div></section>
  </main><PublicFooter/></div>
}
