<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

// APPOINTMENTS.appointment_code — the stable, server-owned, human-readable reference (APT-2026-000123) shown to
// people. It is generated by PostgreSQL itself (a sequence behind the column DEFAULT), so every insert gets one no
// matter which code path creates the row and React never derives it. Existing rows are backfilled deterministically in
// id order using each appointment's creation year (Asia/Manila). A trigger makes the code immutable. The bigint id
// stays internal and public_id stays the API identity; the code is display/reference only.
return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
            CREATE SEQUENCE appointment_code_seq;

            ALTER TABLE appointments ADD COLUMN appointment_code varchar(20);

            UPDATE appointments a SET appointment_code = s.code
            FROM (
                SELECT id, 'APT-' || to_char(created_at AT TIME ZONE 'Asia/Manila', 'YYYY') || '-'
                    || lpad(nextval('appointment_code_seq')::text, 6, '0') AS code
                FROM (SELECT id, created_at FROM appointments ORDER BY id) ordered
            ) s
            WHERE a.id = s.id;

            ALTER TABLE appointments
                ALTER COLUMN appointment_code SET DEFAULT ('APT-' || to_char(now() AT TIME ZONE 'Asia/Manila', 'YYYY') || '-'
                    || lpad(nextval('appointment_code_seq')::text, 6, '0')),
                ALTER COLUMN appointment_code SET NOT NULL,
                ADD CONSTRAINT appointments_appointment_code_unique UNIQUE (appointment_code);

            ALTER SEQUENCE appointment_code_seq OWNED BY appointments.appointment_code;

            CREATE OR REPLACE FUNCTION appointments_code_immutable() RETURNS trigger AS $$
            BEGIN
                IF NEW.appointment_code IS DISTINCT FROM OLD.appointment_code THEN
                    RAISE EXCEPTION 'appointment_code is immutable';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER appointments_code_immutable
                BEFORE UPDATE OF appointment_code ON appointments
                FOR EACH ROW EXECUTE FUNCTION appointments_code_immutable();
        SQL);
    }

    public function down(): void
    {
        DB::unprepared(<<<'SQL'
            DROP TRIGGER IF EXISTS appointments_code_immutable ON appointments;
            DROP FUNCTION IF EXISTS appointments_code_immutable();
            ALTER TABLE appointments DROP CONSTRAINT IF EXISTS appointments_appointment_code_unique;
            ALTER TABLE appointments DROP COLUMN IF EXISTS appointment_code;
            DROP SEQUENCE IF EXISTS appointment_code_seq;
        SQL);
    }
};
