<?php
namespace App\Http\Controllers;
use App\Enums\Role;
use App\Http\Controllers\Concerns\ReadsIdempotencyKey;
use App\Http\Resources\{InvoiceResource,ReceiptResource};
use App\Models\{CommandKey,Invoice,Receipt,Treatment};
use App\Services\Billing\{BillingException,BillingService};
use App\Support\IdempotentCommand;
use Illuminate\Http\Request;
use Closure;
class BillingController extends Controller { use ReadsIdempotencyKey; public function __construct(private readonly BillingService $billing){}
 private function fail(BillingException $e){return response()->json($e->responseBody(),$e->getStatusCode());}
 public function treatments(Request $r){abort_unless(in_array($r->user()->role,[Role::Staff,Role::Owner],true),403);return response()->json(['data'=>$this->billing->treatments($r->user())->map(function($row){$t=$row['treatment'];return ['id'=>$t->public_id,'status'=>$t->status,'completed_at'=>$t->completed_at?->toIso8601String(),'patient'=>['id'=>$t->visit->patient->public_id,'name'=>$t->visit->patient->person?->fullName()],'branch'=>['id'=>$t->visit->branch->legacy_ref,'name'=>$t->visit->branch->name],'services'=>$t->procedures->map(fn($p)=>['code'=>$p->service_code,'name'=>$p->service_name,'quantity'=>$p->quantity])->values(),'billing_state'=>$row['billing_state'],'pricing_unavailable'=>$row['pricing_unavailable'],'invoice'=>$row['invoice']?->public_id];})]);}
 public function index(Request $r){abort_unless(in_array($r->user()->role,[Role::Staff,Role::Owner],true),403);$q=Invoice::visibleTo($r->user())->with(['lines.servicePrice','treatment','visit','patient.person','branch','payment','receipt','histories'])->latest('id');return InvoiceResource::collection($q->limit(200)->get());}
 public function mine(Request $r){abort_unless($r->user()->role===Role::Patient&&$r->user()->patient,403);$rows=Invoice::where('patient_id',$r->user()->patient->id)->with(['lines.servicePrice','treatment','visit','patient.person','branch','payment','receipt'])->latest('id')->limit(200)->get();return InvoiceResource::collection($rows);}
 public function receiptsMine(Request $r){abort_unless($r->user()->role===Role::Patient&&$r->user()->patient,403);return ReceiptResource::collection(Receipt::whereHas('invoice',fn($q)=>$q->where('patient_id',$r->user()->patient->id))->with('invoice')->latest('id')->limit(200)->get());}
 public function show(Request $r,Invoice $invoice){abort_unless(Invoice::visibleTo($r->user())->whereKey($invoice->id)->exists(),403);return new InvoiceResource($invoice->load(['lines.servicePrice','treatment','visit','patient.person','branch','payment','receipt','histories']));}
 public function create(Request $r,Treatment $treatment){$key=$this->idempotencyKey($r,true); try{return $this->command($r,$key,'billing.draft',['treatment'=>$treatment->public_id],fn()=>[$this->billing->createDraft($r->user(),$treatment),201],fn($row)=>(new InvoiceResource($row->load(['lines.servicePrice','treatment','visit','patient.person','branch','payment','receipt','histories'])))->response($r)->getData(true));}catch(BillingException $e){return $this->fail($e);}}
 public function review(Request $r,Invoice $invoice){$key=$this->idempotencyKey($r,true);$v=$r->validate(['expected_revision'=>['required','integer','min:1']]);try{return $this->command($r,$key,'billing.review',['invoice'=>$invoice->public_id,'expected_revision'=>(int)$v['expected_revision']],fn()=>[$this->billing->transition($r->user(),$invoice,'Review',(int)$v['expected_revision']),200],fn($row)=>(new InvoiceResource($row->load(['lines.servicePrice','histories'])))->response($r)->getData(true));}catch(BillingException $e){return $this->fail($e);}}
 public function issue(Request $r,Invoice $invoice){$key=$this->idempotencyKey($r,true);$v=$r->validate(['expected_revision'=>['required','integer','min:1']]);try{return $this->command($r,$key,'billing.issue',['invoice'=>$invoice->public_id,'expected_revision'=>(int)$v['expected_revision']],fn()=>[$this->billing->transition($r->user(),$invoice,'Issued',(int)$v['expected_revision']),200],fn($row)=>(new InvoiceResource($row->load(['lines.servicePrice','histories','payment','receipt'])))->response($r)->getData(true));}catch(BillingException $e){return $this->fail($e);}}
 public function pay(Request $r,Invoice $invoice){$key=$this->idempotencyKey($r,true);$v=$r->validate(['expected_revision'=>['required','integer','min:1'],'method'=>['required','in:Cash,Card/POS,Bank Transfer,E-Wallet'],'amount'=>['nullable','string','regex:/^\d+(\.\d{1,2})?$/'],'external_reference'=>['nullable','string','max:160']]);$payload=['invoice'=>$invoice->public_id,'expected_revision'=>(int)$v['expected_revision'],'method'=>$v['method'],'amount'=>$v['amount']??null,'external_reference'=>$v['external_reference']??null];try{return $this->command($r,$key,'billing.payment',$payload,fn()=>[$this->billing->pay($r->user(),$invoice,(int)$v['expected_revision'],$v['method'],$v['external_reference']??null,$v['amount']??null),200],fn($row)=>(new InvoiceResource($row->load(['lines.servicePrice','histories','payment','receipt'])))->response($r)->getData(true));}catch(BillingException $e){return $this->fail($e);}}
 private function command(Request $r,string $key,string $name,array $payload,Closure $work,Closure $present){return IdempotentCommand::run(CommandKey::class,$r->user(),$key,$name,$payload,function()use($work,$present){[$row,$status]=$work();return [$present($row),$status];},fn()=>new BillingException(409,'idempotency_key_reused','This Idempotency-Key was already used for a different billing request.'));}
}
