<?php
namespace App\Services\Billing;
use App\Enums\Role;
use App\Models\{BillingCutover,Invoice,InvoiceHistory,InvoiceLine,Payment,Receipt,Treatment,User,UserBranchScope};
use App\Services\Hmo\HmoFinancialGate;
use App\Services\Pricing\{PriceResolver,PriceUnavailable};
use App\Support\ClinicClock;
use Illuminate\Support\Facades\DB;

final class BillingService {
    public function __construct(private readonly PriceResolver $prices, private readonly HmoFinancialGate $gate) {}
    public function treatments(User $actor) { return Treatment::visibleTo($actor)->where('status','Completed')->with(['visit.patient.person','visit.branch','procedures.service'])->get()->map(function (Treatment $t) { $missing=[]; foreach ($t->procedures as $line) { if ($this->prices->resolve($line->service,$t->visit->branch,$t->visit->clinic_date->format('Y-m-d')) instanceof PriceUnavailable) $missing[]=['line_no'=>$line->line_no,'service'=>$line->service->legacy_ref,'name'=>$line->service->name]; } $invoice=Invoice::where('treatment_id',$t->id)->first(); return ['treatment'=>$t,'invoice'=>$invoice,'billing_state'=>$invoice?'already_invoiced':($missing?'pricing_unavailable':'ready_for_draft'),'pricing_unavailable'=>$missing]; }); }
    public function createDraft(User $actor,Treatment $treatment): Invoice {
        $this->staffBranch($actor,$treatment->visit->branch_id);
        return DB::transaction(function() use($actor,$treatment){
            $t=Treatment::whereKey($treatment->id)->lockForUpdate()->with(['visit.patient','visit.branch','procedures.service'])->firstOrFail();
            if($t->status!=='Completed') throw new BillingException(422,'invalid_treatment_status','Only completed Treatments can be billed.');
            $cut=BillingCutover::query()->firstOrFail(); if(!$t->completed_at || $t->completed_at->lt($cut->established_at)) throw new BillingException(422,'treatment_before_cutover','This Treatment was completed before M11 billing became authoritative.');
            if($existing=Invoice::where('treatment_id',$t->id)->with(['lines','payment','receipt'])->first()) return $existing;
            $gross='0.00'; $rows=[]; $fail=[];
            foreach($t->procedures as $line){ $resolved=$this->prices->resolve($line->service,$t->visit->branch,$t->visit->clinic_date->format('Y-m-d')); if($resolved instanceof PriceUnavailable){$fail[]=['line_no'=>$line->line_no,'service'=>$line->service->legacy_ref,'name'=>$line->service->name];continue;} $unit=$resolved->amount(); $total=$this->mul($unit,$line->quantity); $gross=$this->add($gross,$total); $rows[]=['line'=>$line,'resolved'=>$resolved,'unit'=>$unit,'total'=>$total]; }
            if($fail) throw new BillingException(422,'pricing_unavailable','Authoritative pricing is required before creating this invoice.', ['services'=>$fail]);
            $n=DB::selectOne("select nextval('m11_invoice_number_seq') as n")->n; $number='INV-'.now()->format('Y').'-'.str_pad((string)$n,6,'0',STR_PAD_LEFT);
            $invoice=Invoice::create(['treatment_id'=>$t->id,'visit_id'=>$t->visit_id,'patient_id'=>$t->visit->patient_id,'branch_id'=>$t->visit->branch_id,'invoice_number'=>$number,'status'=>'Draft','revision'=>1,'gross_amount'=>$gross,'hmo_coverage_amount'=>'0.00','patient_responsibility_amount'=>$gross,'paid_amount'=>'0.00','created_by_user_id'=>$actor->id,'updated_by_user_id'=>$actor->id]);
            foreach($rows as $i=>$r) InvoiceLine::create(['invoice_id'=>$invoice->id,'service_id'=>$r['line']->service_id,'service_price_id'=>$r['resolved']->version->id,'line_no'=>$i+1,'service_code'=>$r['line']->service_code,'service_name'=>$r['line']->service_name,'quantity'=>$r['line']->quantity,'unit_price'=>$r['unit'],'line_total'=>$r['total']]);
            $this->history($invoice,$actor,'invoice.created',null,'Draft'); return $invoice->load(['lines','treatment','visit.patient.person','branch','payment','receipt','histories']);
        },3);
    }
    public function transition(User $actor,Invoice $invoice,string $to,int $expected):Invoice {
        $this->staffBranch($actor,$invoice->branch_id); return DB::transaction(function()use($actor,$invoice,$to,$expected){$i=Invoice::whereKey($invoice->id)->lockForUpdate()->with(['lines','visit'])->firstOrFail(); if($i->revision!==$expected)throw new BillingException(409,'stale_revision','Invoice changed; reload before continuing.'); if($to==='Review'){if($i->status!=='Draft')throw new BillingException(422,'invalid_invoice_state','Only Draft invoices can be reviewed.'); $from=$i->status;$i->update(['status'=>'Review','revision'=>$i->revision+1,'updated_by_user_id'=>$actor->id]);$this->history($i,$actor,'invoice.reviewed',$from,'Review');return $i->fresh(['lines','histories']);} if($to==='Issued'){if($i->status!=='Review')throw new BillingException(422,'invalid_invoice_state','Only Review invoices can be issued.');$gate=$this->gate->forTreatment($i->treatment()->firstOrFail()); if($gate['blocks_invoice_issue'])throw new BillingException(422,'hmo_financial_hold','HMO financial decision is required before issuing this invoice.',['gate'=>$gate]);$coverage=in_array($gate['coverage_status'],['approved'],true)?$this->min((string)($gate['approved_amount']??'0.00'),(string)$i->gross_amount):'0.00';$resp=$this->sub((string)$i->gross_amount,$coverage);$paid=$resp==='0.00'?'0.00':(string)$i->paid_amount;$status=$resp==='0.00'?'Paid':'Issued';$i->update(['status'=>$status,'revision'=>$i->revision+1,'hmo_status'=>$gate['status'],'hmo_approved_amount'=>$gate['approved_amount'],'hmo_coverage_amount'=>$coverage,'patient_responsibility_amount'=>$resp,'paid_amount'=>$paid,'settlement_type'=>$resp==='0.00'?'full_hmo_coverage':null,'issued_at'=>ClinicClock::now(),'paid_at'=>$resp==='0.00'?ClinicClock::now():null,'updated_by_user_id'=>$actor->id]);$this->history($i,$actor,'invoice.issued','Review',$status,$resp==='0.00'?'full_hmo_coverage':null);return $i->fresh(['lines','histories','payment','receipt']);} throw new BillingException(422,'invalid_invoice_state','Unsupported invoice transition.');},3);
    }
    public function pay(User $actor,Invoice $invoice,int $expected,string $method,?string $reference,?string $submittedAmount=null):Invoice { $this->staffBranch($actor,$invoice->branch_id); return DB::transaction(function()use($actor,$invoice,$expected,$method,$reference,$submittedAmount){$i=Invoice::whereKey($invoice->id)->lockForUpdate()->with(['lines','visit','payment','receipt'])->firstOrFail();if($i->revision!==$expected)throw new BillingException(409,'stale_revision','Invoice changed; reload before continuing.');if($i->status!=='Issued')throw new BillingException(422,$i->status==='Paid'?'already_paid':'invalid_invoice_state','This invoice is not payable.');$gate=$this->gate->forTreatment($i->treatment()->firstOrFail());if($gate['blocks_payment'])throw new BillingException(422,'hmo_financial_hold','HMO financial decision is required before payment.',['gate'=>$gate]);$current=$gate['coverage_status']==='approved'?$this->min((string)($gate['approved_amount']??'0.00'),(string)$i->gross_amount):'0.00';if($submittedAmount !== null && $this->cents($submittedAmount) !== $this->cents($this->sub((string)$i->patient_responsibility_amount,(string)$i->paid_amount))) throw new BillingException(422,'invalid_payment_amount','Payment must equal the full current balance.');if($current!== (string)$i->hmo_coverage_amount || (string)($gate['status']??'') !== (string)($i->hmo_status??''))throw new BillingException(409,'financial_state_changed','The HMO financial outcome changed after issue.');$balance=$this->sub((string)$i->patient_responsibility_amount,(string)$i->paid_amount);if($balance==='0.00')throw new BillingException(422,'already_paid','This invoice is already settled.');if(in_array($method,['Card/POS','Bank Transfer','E-Wallet'],true)&&!$reference)throw new BillingException(422,'invalid_payment_reference','An external reference is required for this payment method.');$payment=Payment::create(['invoice_id'=>$i->id,'amount'=>$balance,'method'=>$method,'external_reference'=>$reference,'recorded_by_user_id'=>$actor->id,'recorded_at'=>ClinicClock::now()]);$rn=DB::selectOne("select nextval('m11_receipt_number_seq') as n")->n;$receipt=Receipt::create(['payment_id'=>$payment->id,'invoice_id'=>$i->id,'receipt_number'=>'RCT-'.now()->format('Y').'-'.str_pad((string)$rn,6,'0',STR_PAD_LEFT),'amount'=>$balance,'method'=>$method,'external_reference'=>$reference,'issued_at'=>ClinicClock::now()]);$i->update(['status'=>'Paid','paid_amount'=>$balance,'paid_at'=>ClinicClock::now(),'revision'=>$i->revision+1,'updated_by_user_id'=>$actor->id]);$this->history($i,$actor,'invoice.paid','Issued','Paid');return $i->fresh(['lines','histories','payment','receipt']);},3); }
    private function history(Invoice $i,User $a,string $event,?string $from,?string $to,?string $settlement=null):void{InvoiceHistory::create(['invoice_id'=>$i->id,'event'=>$event,'from_status'=>$from,'to_status'=>$to,'settlement_type'=>$settlement,'snapshot'=>['gross_amount'=>(string)$i->gross_amount,'hmo_coverage_amount'=>(string)$i->hmo_coverage_amount,'patient_responsibility_amount'=>(string)$i->patient_responsibility_amount,'paid_amount'=>(string)$i->paid_amount],'actor_user_id'=>$a->id,'occurred_at'=>ClinicClock::now()]);}
    private function staffBranch(User $a,int $branch):void{if($a->role!==Role::Staff||!UserBranchScope::where('user_id',$a->id)->where('branch_id',$branch)->exists())throw new BillingException(403,'forbidden','Staff branch access is required.');}
    private function cents(string $v):int{$v=trim($v);if(!preg_match('/^\d+(?:\.\d{1,2})?$/',$v))throw new BillingException(500,'invalid_decimal','Invalid stored financial decimal.');$p=explode('.',$v);return ((int)$p[0])*100+(int)str_pad($p[1]??'0',2,'0');}
    private function dec(int $c):string{return number_format($c/100,2,'.','');}
    private function add(string $a,string $b):string{return $this->dec($this->cents($a)+$this->cents($b));} private function sub(string $a,string $b):string{return $this->dec($this->cents($a)-$this->cents($b));} private function mul(string $a,int $q):string{return $this->dec($this->cents($a)*$q);} private function min(string $a,string $b):string{return $this->dec(min($this->cents($a),$this->cents($b)));}
}
